AliceO2Group/Bookkeeping

lib/public/views/Logs/Create/index.js
lib/public/views/Logs/Logs.js

Instructions to verify: Go to the create screen and create a title like: # Sample Text, hit enter and the grey line should cover the whole width of the box now

fix: Set width to auto in the markdown box when creating an entry

---

lib/database/adapters/UserAdapter.js
lib/database/migrations/20200914120527-logs-remove-user-constraint.js
lib/database/seeders/20200508094502-logs.js
lib/public/components/Post/index.js
lib/usecases/log/CreateLogUseCase.js
spec/openapi-source.yaml
spec/openapi.yaml

https://alice.its.cern.ch/jira/browse/O2B-348

Anonymous logs

---

scripts/wait-for-it.sh

echo sends a newline character which causes some server software to report an error message about an invalid HTTP request. By adding the '-n' flag the echo command can be used to open the port without sending anything.

Updated wait-for-it.sh

---

test/public/flps/detail.test.js
test/public/flps/overview.test.js
test/public/logs/create.test.js
test/public/logs/detail.test.js
test/public/logs/overview.test.js
test/public/runs/detail.test.js
test/public/runs/overview.test.js
test/public/subsystems/detail.test.js
test/public/subsystems/overview.test.js
test/public/tags/create.test.js
test/public/tags/detail.test.js
test/public/tags/overview.test.js

In regards to the usage of page.waitForTimeout(milliseconds) see the API description of page.waitFor(selectorOrFunctionOrTimeout[, options[, ...args]])
> https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pagewaitforselectororfunctionortimeout-options-args
In regards to the load option in the page.goto(url[, options]) calls, 
> **networkidle0** - consider navigation to be finished when there are no more than 0 network connections for at least 500 ms.

Refactored Puppeteer calls in the test suite

---

cpp-api-client/CMakeLists.txt

The relevant alidist recipe: https://github.com/alisw/alidist/pull/2666
As soon as it's merged the compilation will be as simple as: `aliBuild build Bookkeeping`
Still to be fixed:

Use CMake targets and transitive deps in C++ binding

---

lib/config/jwt.js

`expiration` and `maxAge`  have been set to `1y`

JWT Default configuration 1 year

---

.github/workflows/release.yml

This is required to install Bookkeeping without connection to npm registry.
After creating a release (tag is not enough) this workflow will automatically upload TARBall to assets with all necessary deps.

Add GH workflow to create bundled TARballs on release

---

lib/server/routers/runs.router.js
lib/usecases/run/EndRunUseCase.js
lib/usecases/run/StartRunUseCase.js
package-lock.json
package.json

Until token management is ready we need to make sure that all subsystem will be able to access `/api/runs` route

[O2-2512] Make /api/runs route public

---

lib/public/components/Filters/LogsFilter/runs.js
lib/public/views/Runs/Runs.js

Now you can erase the number without using the button.

Small fix to setRunsFilter

---

lib/public/views/Runs/Details/index.js
lib/public/views/Runs/Runs.js

Added a new method that now checks for the switching of tabs to clear out the not required data.
Replaced the onRemove on the whole div to an onclick on the two tabs to switch between them.
Keeping the onRemove and passing a parameter with the current tab would either cause one of the two active tabs to get emptied on the tag update or cause the renderer to endlessly update when switching between flps and logs.

[O2B-462] - Run Details clears log on tag update

---

.github/CODEOWNERS
.github/pull_request_template.md
.github/workflows/release.yml
package.json

* Adds `CODEOWNERS` file to automatically add reviewers;
* Adds new GH workflow that will automatically release an npm module to NPM registry when a release is created;
* Adds GH pull request template
* Adds `nodejs 16` to `release` and `upload tar` workflows
* Migrate to use `checkout/v2`
* Migrate to use `setup-node/v2`
* Specify `bundledDependencies` when packing as NPM
* Specify `files` to bundle when packing as NPM

[O2B-467] Add Bookkeping GH templates and extend on current workflows

---

lib/public/components/Table/rows.js
lib/public/views/About/Overview/index.js
lib/public/views/Home/Overview/index.js
lib/public/views/Logs/ActiveColumns/index.js
lib/public/views/Logs/Overview/index.js
lib/public/views/Runs/ActiveColumns/index.js
lib/public/views/Runs/Overview/index.js
test/public/home/overview.test.js
test/public/logs/create.test.js
test/public/logs/overview.test.js
test/public/runs/overview.test.js

Added a button to logs and runs tables to direct the user to a specific log/run, to enable copying of the rows without being redirected. The docker tests were modified accordingly, and tested within browser.

[O2B-460] Adding details button to logs/runs tables.

---

lib/usecases/log/CreateLogUseCase.js
test/e2e/logs.test.js
test/public/home/overview.test.js
test/usecases/log/CreateLogUseCase.test.js

There was a bug where when duplicate run numbers are inserted, an internal server error would appear and not save the data. This is now fixed and tested with e2e and use case tests.

[O2B-508] When creating logs double run numbers are filtered in the backend

---

lib/database/seeders/20200511151010-tags.js
lib/domain/dtos/GetAllTagsDto.js
lib/server/controllers/tags.controller.js
lib/server/routers/tags.router.js
lib/usecases/tag/GetAllTagsUseCase.js
test/e2e/logs.test.js
test/usecases/tag/GetAllTagsUseCase.test.js

* Builds on `listTags` to accept filters such as: `ids, texts, emails, mattermosts`
* Adds filter validation
* Returns 204 status if no data is found
* Adds corresponding tests
* Makes GET API `/api/tags/` public

[O2B-505] Improve listTags API to accept filters for tags retrieval

---

CHANGELOG.md
lib/public/views/About/Overview/index.js
package-lock.json
package.json

* Notable changes for users:
* RUN Filters Improvements:
* Allows users to filter by DD, DCS, EPN with ON,OFF or ANY
* RUN Exports:
* [FIXED] - exporting a list of runs by their runNumber would not retrieve the whole list;
* `o2TimeStart`, `o2TimeStop`, `o2TrgStart`, `o2TrgStop` converts timestamps to user friendly date formats;
* LOG Creation:
* [FIXED] - removes duplicated `runNumbers` when creating a log entry instead of throwing error;
* TAGS Page:
* Displays new tag information: `email` and `mattermost` groups;
* Notable changes for developers:
* `/api/runs` - listRuns - accepts multiple `runNumbers` for filtering;
* `/api/runs` - listRuns - improves filtering for `dcs`, `dd_flp`, `epn`;
* `/api/tags` - listTags - accepts multiple `ids`, `texts`, `emails` and/or `mattermosts` as …

Release 0.24.0

---

lib/public/components/Pagination/pageSelector.js
lib/public/views/Logs/Logs.js
lib/public/views/Runs/Runs.js

Increased the scroll update delay to give the system more time to set the right value. Notifies before the fetch so the updates are notified to the components faster.

[O2B-507] - Infinite mode in Run Statistics table displays duplicates

---

lib/public/components/TagDetail/index.js
lib/public/views/Runs/Details/editTagsPanel.js
lib/public/views/Tags/Details/index.js

Bug and typo is fixed.
Steps to reproduce in the ticket or below:
1) Open the details of one tag.
2) Edit it.
3) Without SAVE or CANCEL, re-open the TAGS overview and select another tag's detail page.
4) Edit it.

[O2B-571] Tag edit mode saves old edit data on page switch

---

lib/database/migrations/20220511102048-update-run-detectors-column.js
lib/domain/dtos/StartRunDto.js
spec/openapi-source.yaml
spec/openapi.yaml
test/e2e/runs.test.js
test/usecases/run/StartRunUseCase.test.js
test/usecases/run/index.js

`runs.detectors` column was set to `ENUM` which only allowed one value to be set;
RUNS in AliECS can now accept multiple detectors so:
*  a validation is done on server side that it contains only accepted values
* `runs.detectors` columns is updated to `String` from `Enum`

[O2B-567] Migrate runs.detectors to string type

---

docs/data-model.md
lib/database/adapters/EorReasonAdapter.js
lib/database/adapters/ReasonTypeAdapter.js
lib/database/adapters/RunAdapter.js
lib/database/migrations/20220513075839-create-reason-type-table.js
lib/database/migrations/20220513153414-crete-eor-reason-table.js
lib/database/models/eorreason.js
lib/database/models/index.js
lib/database/models/reasontype.js
lib/database/models/run.js
lib/database/repositories/ReasonTypeRepository.js
lib/database/repositories/index.js
lib/database/seeders/20220513083459-reason-types.js
lib/database/seeders/20220513153907-eor-reason.js

PR which:
* adds new models, adapters, migrations and seeders files for `eor_reasons` and `reason_type`
* database model documentation
A run has many `eor_reasons` while an `eor_reason` has one `reason_type`

[O2B-574] Add runs eor_reasons and reason_types tables

---

lib/database/adapters/EorReasonAdapter.js
lib/database/adapters/RunAdapter.js
lib/usecases/run/GetRunUseCase.js
spec/openapi-source.yaml
spec/openapi.yaml
test/openapi.test.js
test/usecases/run/GetRunUseCase.test.js

* Updates the `GetRunUseCase` to include retrieval of EOR-reason
* EOR-reason will include at the same level the details of the general `reason_type`
`RUN` hasMany `eor_reasons`
`eor_reason` has one `reason_type`

[O2B-576] Adapt retrieval of run to include eor

---

lib/database/repositories/EorReasonRepository.js
lib/domain/dtos/UpdateRunDto.js
lib/usecases/run/UpdateRunUseCase.js
test/e2e/runs.test.js
test/usecases/run/UpdateRunUseCase.test.js

PR Which:
* Extends the current `UpdateRunUseCase` to update `eor_reasons` table as well if passed within the run object
* Fixes error response as this was not being sent if update of the run failed;
* Adds tests accordingly

[O2B-565] UpdateRunsUseCase to include eor reason and improve error response

---

lib/public/Model.js
lib/public/components/Filters/FlpsFilter/index.js
lib/public/components/Filters/LogsFilter/index.js
lib/public/components/Filters/RunsFilter/index.js
lib/public/utilities/frontLink.js
lib/public/views/Envs/ActiveColumns/envsActiveColumns.js
lib/public/views/Envs/Overview/index.js
lib/public/views/Flps/ActiveColumns/flpsActiveColumns.js
lib/public/views/Flps/Overview/index.js
lib/public/views/Home/Overview/index.js
lib/public/views/LhcFills/ActiveColumns/lhcFillsActiveColumns.js
lib/public/views/LhcFills/Overview/index.js
lib/public/views/Logs/ActiveColumns/logsActiveColumns.js
lib/public/views/Logs/ActiveColumns/reducedLogsActiveColumns.js
lib/public/views/Logs/Logs.js
lib/public/views/Logs/Overview/index.js
lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
lib/public/views/Runs/Details/index.js
lib/public/views/Runs/Overview/exportRunsModal.js
lib/public/views/Runs/Overview/index.js
lib/public/views/Runs/Runs.js
lib/public/views/Subsystems/Details/index.js
lib/public/views/Tags/ActiveColumns/tagsActiveColumns.js
lib/public/views/Tags/Details/index.js
lib/public/views/Tags/Overview/index.js
test/public/logs/overview.test.js

[O2B-659] Make active columns independent of the model + refactoring

---

database/CHANGELOG.md
docs/data-model.md
go-api-client/Example.go
go-api-client/openapi-source.yaml
go-api-client/src/BookkeepingApi.go
go-api-client/src/go-client-generated/api/swagger.yaml
go-api-client/src/go-client-generated/docs/Run.md
go-api-client/src/go-client-generated/model_run.go
lib/database/adapters/RunAdapter.js
lib/database/migrations/20220726074211-runs-lhc-period.js
lib/database/models/run.js
lib/database/seeders/20200713103855-runs.js
lib/domain/dtos/EndRunDto.js
spec/openapi-source.yaml
spec/openapi.yaml
test/e2e/runs.test.js
test/usecases/run/EndRunUseCase.test.js

CHANGELOG will be updated with ticket O2B-627
Extra field is added within the run table:
`lhcPeriod` - string
This period can be updated by using the endpoint PATCH api/runs/:id

[O2B-657] Store lhcPeriod value in runs

---

lib/server/controllers/logs.controller.js
package-lock.json
package.json

Notification Service now allows receiving a list of `runNumbers`. This will be turned into a list-string separated by comma and sent to Kafka;
In the next iteration, the notification service will not be placed in the controller anymore but in a use case

[O2B-664] Include run numbers in log entry notification

---

lib/public/utilities/formatting/formatRunType.js

Fixes the bug where there are no run types.
To replicate this remove the `up` function in run type seeder for an empty function: 
`up: async ({ context: { queryInterface } }) =>{},`
and comment out all the `run_type_id` values within the run seeder.
Re-seed the database and open a run or run overview on the webpage.

Fix for empty run type

---

.github/pull_request_template.md

Update GH PR templates to fit the needs of the new changelog system:
- Put in each PR the changelogs for this particular PR
- Once the PR is merged, update the CHANGELOGS files in the release branch

Update PR template for new changelog system

---

lib/database/adapters/RunAdapter.js
lib/database/seeders/20200713103855-runs.js
lib/public/components/RunDetail/index.js
test/e2e/runs.test.js

When requesting a run with tf/ctf/other file with the value of '0' the API would return null and show a - in the webpage. Now a '0' value is returned and shown in the details page

[O2B-750] File size is shown as '0' instead of null

---

lib/database/repositories/LogRunsRepository.js
lib/database/tables/logruns.js
lib/public/components/Filters/LogsFilter/runs.js
lib/public/views/Logs/Logs.js
lib/usecases/log/GetAllLogsUseCase.js
test/e2e/logs.test.js
test/public/defaults.js
test/public/logs/overview.test.js
test/public/runs/detail.test.js
test/usecases/log/GetAllLogsUseCase.test.js

- Log runs filter applies on run number and not on run ID anymore

[O2B-779] Filter log on run number not run id

---

lib/server/services/detector/DetectorService.js
lib/server/services/detector/getAllDetectors.js
lib/server/services/run/getRun.js
test/e2e/detectors.test.js
test/server/services/detector/DetectorService.test.js

- Detectors are now sorted in the run's detector filter

[O2B-794] Sort detectors in run filtering

---

Dockerfile

- Bumped version of nodejs base image from `node:16.16.0-alpine3.16` to `node:16.19.0-alpine3.16`

[O2B-812] Bump docker nodejs base image

---

lib/server/services/log/createLog.js
package-lock.json
package.json

Notable changes for users: NA
- NotifcationService `send` method, now expects a general message without project specific fields. The message is built on BKP side
- Existing message field criteria was taken from: https://github.com/AliceO2Group/WebUi/pull/1796/files#diff-c025c39557c4ea200883fe9f312aff9ebc69528d9c724c71a452fc6e7c8bf826L77
Changes made to the database: NA

[O2B-766] Add log-id and parent-log-id to kafka message

---

docs/RUN_DEFINITIONS.md
lib/server/services/run/getRunDefinition.js
test/lib/server/services/run/getRunDefinition.test.js
test/mocks/mock-run.js

- `CALIBRATION` definition will now look for `NOISE` as runType as well
-
-

[O2B-842] Add NOISE as run type for CALIBRATION run definition

---

lib/public/views/Logs/Overview/index.js

- The EOS report button is not available on log display

[O2B-841] Remove EOS report link from logs pages

---

lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js
lib/server/services/shift/formatShiftDate.js
test/mocks/mock-eos-report.js
test/public/eosReport/creation.test.js

- The EoS report now have envs & runs timestamps displayed as dates in the shifter timezone and format

[O2B-840] Format timestamp in shifter format

---

lib/server/services/eosReport/EosReportService.js
test/lib/server/services/eosReport/EosReportService.test.js

- The current user is used as author of EoS report log

[O2B-853] Use current user as EoS report log author

---

lib/server/services/shift/ShiftService.js

- The time to fill EoS report after the end of shift is now 30min (previously 2h)

[O2B-856] Update EoS report cutoff from 2h to 30min

---

lib/public/components/common/markdown/markdown.js
lib/public/views/EosReport/create/eosReportCreationComponent.js
lib/public/views/Logs/Create/logCreationComponent.js
test/public/eosReport/creation.test.js

- Fixed bug which reseted the input data of EoS report's shifter name when clicking in it while it is focused

[O2B-861] Fix data reset when clicking in EoS report's shifter-name input

---

lib/public/components/Pagination/PaginationModel.js
lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js

This commit is only a simple patch, the infinite scroll is flawed and do not handle at all the concurrency issues.
Data fetching should be separated from display.
This patch is only applied on LHC fill, other similar pages stay the same. This code should be factorized between all overview pages.
- LHC fill overview infinite scroll now display valid data

[O2B-864] Fix LHC fill infinite scroll

---

test/public/defaults.js

- Use new headless chrome for pupeteer tests

[O2B-878] Use new headless chrome for puppeteer tests

---

lib/public/utilities/formatting/formatFileSize.js
lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
lib/public/views/Runs/Details/runDetailsConfiguration.js
test/public/lhcFills/detail.test.js

- File size are now displayed in GB in run details and LHC fill details

[O2B-880] Display file size in human readable format

---

CHANGELOG.md
lib/public/views/About/Overview/index.js
package-lock.json
package.json

* Notable changes for users:
*  Runs will be definied as Definition `PHYSICS` only if they include both detectors `FT0` and `ITS`. This change will also apply to previous runs

[release/0.55.2] 

---

lib/domain/dtos/DtoFactory.js
lib/server/controllers/dplProcess.controller.js
lib/server/routers/dplProcess.router.js
lib/server/routers/index.js
lib/server/services/dpl/DplProcessService.js
test/api/dplProcess.test.js
test/api/index.js
test/lib/server/services/dpl/DplProcessService.test.js
test/lib/server/services/dpl/index.js
test/lib/server/services/index.js

- An endpoint to fetch all DPL detectors that have at least one executed process for a given run has been added

[O2B-872] Fetch all DPL detectors with at least one executed process

---

lib/public/services/lhcFill/LhcFillStatisticsExtractor.js
lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js
test/public/lhcFills/detail.test.js

- Adds total TF size display to LHC fill details, renamed 'total CTF' to 'total CTF size'

[O2B-886] Add total TF size alongside the total CTF size on lhc fill display

---

lib/server/controllers/dplProcess.controller.js
lib/server/routers/dplProcess.router.js
lib/server/services/dpl/DplProcessService.js
lib/server/services/dpl/getDplDetector.js
lib/server/services/dpl/getDplDetectorOrFail.js
test/api/dplProcess.test.js
test/lib/server/services/dpl/DplProcessService.test.js

- An endpoint to fetch all DPL processes that have been executed on a given run and detector has been added

[O2B-867] Fetch all DPL processes executed for a given run and detector

---

lib/server/controllers/dplProcess.controller.js
lib/server/routers/dplProcess.router.js
lib/server/services/dpl/DplProcessService.js
lib/server/services/host/getHost.js
lib/server/services/host/getHostOrFail.js
test/api/dplProcess.test.js
test/lib/server/services/dpl/DplProcessService.test.js

- An API endpoint to fetch all the executions of a given process, on a given host for a given run & detector

[O2B-871] Fetch all process executions by host & run & detector

---

lib/public/assets/SmartEditor/README.MD

This PR removes a stale link in the readme for HyperMD. The site appears to have been bought by an advertising company, so visiting it could be a security risk?
Also, HyperMD doesn't appear to be maintained anymore so maybe we should consider using something else?

Remove stale/bad link in local copy of HyperMD

---

lib/public/views/Logs/Details/LogTreeViewModel.js
test/public/logs/create.test.js

- When the log tree view page is displayed for single logs with no replies, the button now shows 'Collapse all' by default

Shows 'Collapse all' button for single logs

---

lib/public/views/Statistics/StatisticsPage.js

- Fill efficiency tooltip displays the correct value

[O2B-963] Fix fill efficiency tooltip value

---

.github/workflows/bookkeeping.yml
.github/workflows/release.yml
package.json

- [NA] if it is a new feature, explain how you plan to use it
- [NA] tests are added
- [NA] documentation was updated or added
* GH actions will now use the NodeJS 18 version as per the production environment
* package.json also specifies minimum engines allowed to use

Update GH action nodejs version

---

lib/usecases/run/GetAllRunsUseCase.js
test/lib/usecases/run/GetAllRunsUseCase.test.js

- Fixed bug for filtering tags using "or"

[O2B-1004] Fix overview runs filtering by tags `or`

---

lib/public/views/Runs/Details/RunPatch.js
lib/public/views/Runs/format/formatRunQuality.js
lib/server/services/run/updateRun.js
test/lib/server/services/run/RunService.test.js

- Allow editing run quality from none to good or test without justification

[O2B-1005] Allow no-justification when run quality goes from none to good or test

---

lib/public/components/Filters/RunsFilter/runNumber.js
lib/public/views/Runs/Overview/index.js
test/public/runs/overview.test.js

- A second input field is visible to filter runs. This input is visible in the main overview screen without opening the filter tab.
- N/A
- N/A
A new search input for the runs overview is created. It is synced with the search bar in the filter. Furthermore, the filter test is expanded to facilitate both filter methods independently.

[O2B-1012] - Filter by run number in overview

---

lib/domain/dtos/filters/RunFilterDto.js
lib/usecases/run/GetAllRunsUseCase.js
test/api/runs.test.js
test/lib/usecases/run/GetAllRunsUseCase.test.js

- Runs API `calibrationStatus` filter is now `calibrationStatuses` (plural)

[O2B-1037] Pluralize calibration statuses filter

---

lib/public/utilities/formatting/formatTimestamp.js

- formatTimestamp function now properly display `0` timestamp value

Handle 0 in formatTimestamp function

---

lib/database/seeders/20220513153907-eor-reason.js
lib/server/services/lhcFill/LhcFillService.js

- Fixed the run order in LHC fill API when some of the runs have EoR reason

[O2B-1050] Fix ordering of LHC fill's related runs (sort them by runNumber)

---

lib/public/Model.js
lib/public/components/NavBar/index.js
test/public/tags/create.test.js

- Replace nav bar `LHC Fills` tab with `LHC` dropdown with two options:
- `LHC Fills`
- `LHC Periods`
- use only one method in model to toggle nav bar dropdowns
- change links id in https://github.com/AliceO2Group/Bookkeeping/pull/1240/files#diff-90f47b96a0752a7ea8dbe41825baf3804e1228ab28f024b599524e0d0ea2c551R47-R49, because of test failure after adding `LHC Fills` as `pageLink`
- NA

[O2B-1045] nav bar adjustment

---

lib/public/views/Runs/ActiveColumns/runsActiveColumns.js

- The link to details page from run overview page do not include all the run info anymore

[O2B-1096] Fix run overview details link

---

lib/public/components/common/selection/infoLoggerButtonGroup/identifierColumnAndActionsDropdown.js

- Environment id is now written in white in the environment overview

[O2B-1097] Write environments ids in white in overview page

---

lib/database/repositories/EnvironmentHistoryItemRepository.js

- None
- Explicitly added an order by created_at date in the environment history query to solve a bug where the tests would sometimes fail due to being in a different order than expected.
- None

[O2B-1104] environment status history API bugfix

---

lib/public/views/Statistics/StatisticsPageModel.js

- Rollback usage of RemoteData.map not already available

[O2B-1087] Rollback usage of RemoteData.map not already available

---

lib/application.js
lib/config/services.js

- NA
- Use scheduled process manager for synchronisation with MonALISA
- NA

[O2B-1125] Use scheduled process manager for synchronisation with MonALISA

---

.github/dependabot.yml

- Excluded chai major release from dependabot updates because it relies on ES6 and project is not there yet

Remove chai major update because it uses ES6

---

lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
test/lib/server/monalisa-synchronization/MonAlisaSynchronizer.test.js

- NA
- Fix usage of lastRunNumber during Data Passes synchronization
- Add test
- NA

Fix usage of lastRunNumber during Data Passes synchronization

---

lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js
test/public/lhcFills/overview.test.js

- Fixed fill statistics not being displayed in fill overview

[O2B-1176] Add LHC fills statistics back to LHC fills overview

---

lib/public/Model.js
lib/public/components/Filters/LogsFilter/author/AuthorFilterModel.js
lib/public/components/Filters/LogsFilter/author/authorFilter.js
lib/public/views/Logs/Overview/index.js

- Added an easy to reach no-anonymous toggle in logs overview

[O2B-1181] Add easy to reach no-anonymous toggle

---

lib/public/services/externalRouting/getInfologgerLinksUrls.js

- When clicking any infologger link, only severity warn, error and fatal are displayed

[O2B-1188] Remove `info` level form infologger links

---

lib/server/controllers/gRPC/GRPCRunController.js
lib/server/services/run/RunService.js

- At the first SB today, we have observed an issue in which lhcPeriodName was not being saved in Bookkeeping
- this was due to the lhcPeriod string from ECS being extracted from relations instead of patch which resulted in a null lhcPeriod being saved
-

[O2B-1201] Extract lhcPeriod from patch and not relations

---

lib/server/services/environment/transitionToErrorLostEnvironments.js
lib/server/services/housekeeping/handleLostRunsAndEnvironments.js
lib/server/services/run/setO2StopOfLostRuns.js

- Fixed spurious runs being marked as stopped few seconds after their creation, and same for envs

[O2B-1195] Don't transition runs & envs created less than 30s ago

---

lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js
test/public/runs/runsPerDataPass.overview.test.js
test/public/runs/runsPerSimulationPass.overview.test.js

- Removed spurious detectors from Runs Per Data Pass and Runs Per Simulation Pass pages
- NA
- NA

Remove spurious detectors from Runs views

---

lib/public/views/SimulationPasses/ActiveColumns/simulationPassesActiveColumns.js
test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js
test/public/simulationPasses/overviewPerLhcPeriod.test.js

- Added runs counts for simulation pass overview
- NA
- NA

[O2B-1177] Add runs counts for simulation pass overview

---

lib/database/adapters/RunAdapter.js
lib/server/controllers/gRPC/GRPCEnvironmentController.js
lib/server/controllers/gRPC/GRPCRunController.js
lib/server/services/environment/EnvironmentService.js

Previously, runs were not parsed (because repeated field in environment proto) and were returned as is in gRPC response. After https://github.com/AliceO2Group/Bookkeeping/pull/1569 the enums of runs are converted from their js value (string expression of enum) to their gRPC counterpart. The issue is that runType in environments were `runTypeId` which made the enums conversion to fail. 
- Fixed the error thrown when updating environment through gRPC API

[O2B-1270] Fix environment update gRPC API

---

.github/dependabot.yml

- Dependabot will not create PRs to update eslint to 9.x

Ignore eslint major upgrade in dependabot

---

lib/public/views/Statistics/charts/efficiencyChartComponent.js

- Fill efficiency is rounded to 2 decimals in statistics tooltip

[O2B-1041] Display fill efficiency with 2 decimals in statistics tooltip

---

cxx-client/include/BookkeepingApi/QcFlagServiceClient.h
cxx-client/src/grpc/services/GrpcQcFlagServiceClient.cpp
cxx-client/src/grpc/services/GrpcQcFlagServiceClient.h

I am adding simple pipe in cxx-client that allows users to call synchronouse QC Flags via gRPC
- Synchronous QC Flags gRPC call can be made
-
-

Synchronous QC flags call in cxx-client

---

lib/database/repositories/QcFlagRepository.js
package.json

- Fixed unnecessary splitting of GAQ periods
- Fixed calculation of timestamps which define gaq_effective_periods, so only flags of detectors which are defined in global_aggregated_quality_detectors are taken into account for the calculation
- NA

[O2B-1364] Fix unnecessary splitting of GAQ periods

---

lib/database/seeders/20220503120937-lhc-fills.js
lib/public/views/LhcFills/Detail/commonLhcFillDisplayConfiguration.js
test/public/lhcFills/detail.test.js

- Display colliding bunches and luminosity on fills details page
- N/A
- N/A

[O2B-1387] Display lumi information on LHC fill details page

---

lib/server/services/qualityControlFlag/QcFlagService.js
test/lib/server/services/qualityControlFlag/QcFlagService.test.js

- Prevented the QC summary color from changing to gray after more than one verification 
- Added separate request to fetch non-verified flags when calculating QC summary
- NA

[O2B-1390] Fix grey QC summary

---

lib/database/migrations/20241105090940-store-run-and-qcflags-timestamps-in-ms.js
lib/database/repositories/EnvironmentHistoryItemRepository.js
lib/server/services/run/setO2StopOfLostRuns.js
lib/server/utilities/timestampToMysql.js
test/api/qcFlags.test.js
test/lib/server/services/qualityControlFlag/QcFlagService.test.js
test/public/flps/overview.test.js

- N/A
- Runs and QC flags timestamps now store milliseconds
- Following columns in runs table has been changed to Datetime(3):
- time_o2_start
- time_trg_start
- first_tf_timestamp
- last_tf_timestamp
- time_trg_end
- time_o2_end
- Following columns in quality_control_flags table has been changed to Datetime(3):
- from
- to
- created_at
- updated_at
- Following columns in quality_control_flag_effective_periods table has been changed to Datetime(3):
- from
- to
- created_at
- updated_at

[O2B-1401] Store runs and QC flags timestamps with ms

---

lib/server/kafka/AliEcsSynchronizer.js
lib/server/services/run/RunService.js
lib/server/services/user/UserService.js
test/lib/server/services/run/RunService.test.js

- N/A
- Fixed users that start/stop runs not being extracted from kafka message
- N/A

[O2B-1366] Fixed user starting/stopping runs not being properly extracted

---

lib/public/components/Pagination/amountSelector.js
test/public/flps/index.js
test/public/flps/overview.test.js

- N/A
- Fixed randomly failing test in FLP frontend tests
- N/A

Attempt at fixing FLP randomly failing tests

---

lib/database/repositories/QcFlagRepository.js
lib/server/services/qualityControlFlag/QcFlagService.js
lib/server/services/run/setO2StopOfLostRuns.js

- N/A
- Use coalesced run time in raw SQL querries
- N/A

[O2B-1403] Use coalesced run timestamps

---

lib/server/kafka/AliEcsSynchronizer.js

- N/A
- Fixed the runs start/stop extraction from AliECS kafka messages
- N/A

[O2B-1418] Improve runs start/stop extraction from kafka

---

lib/public/components/common/form/inputs/DateTimeInputComponent.js

- N/A
- Fixed randomly failing runs test based on timerange selection (start/stop)
- N/A

Fix randomly failing timerange selection in tests

---

lib/public/components/qcFlags/qcFlagsBreadcrumbs.js
lib/public/views/DataPasses/PerSimulationPassOverview/DataPassesPerSimulationPassOverviewPage.js
lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js
lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
lib/public/views/SimulationPasses/AnchoredOverview/AnchoredSimulationPassesOverviewPage.js
lib/public/views/SimulationPasses/PerLhcPeriodOverview/SimulationPassesPerLhcPeriodOverviewPage.js
test/public/qcFlags/forDataPassCreation.test.js
test/public/qcFlags/forDataPassOverview.test.js
test/public/qcFlags/forSimulationPassCreation.test.js
test/public/qcFlags/forSimulationPassOverview.test.js
test/public/qcFlags/gaqOverview.test.js
test/public/qcFlags/synchronousOverview.test.js
test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js

- N/A
- Fixed randomly failing QC tests
- N/A

Fix QC flags tests

---

lib/database/seeders/20220412122043-environments.js
lib/server/services/run/RunService.js
test/lib/server/services/run/RunService.test.js
test/public/envs/detailsPage.test.js

- Add CTP host to flp roles if CTP is enabled
- N/A
- N/A

[O2B-1420] Add CTP readout host to FLP hosts

---

.github/workflows/bookkeeping.yml
.github/workflows/release.yml
Dockerfile
docs/DEVELOPMENT.md
package-lock.json
package.json
test/public/defaults.js

- NA
- Updates min supported NodeJS to 22 to cover next year of Beam Operations
- disables usage of GPU on puppetter as it hangs on docker-alpine (known issue on their repository)
- Updates alpine version as otherwise node 22 was not available
- Updates dependencies for puppeteer as needed due to alpine update
- moves to using `headles: true` instead of `headless: 'new'` with the new puppeteer version
-

[OGUI-1610] Bump NodeJS to v22 for GH Actions

---

.eslintrc
lib/database/adapters/QcFlagAdapter.js
lib/database/migrations/v1/20250217075020-add-qc-flags-deleted-flag.js
lib/database/models/qcFlag.js
lib/database/models/typedefs/SequelizeQcFlag.js
lib/database/repositories/QcFlagRepository.js
lib/database/seeders/20240404100811-qc-flags.js
lib/domain/entities/QcFlag.js
lib/public/app.css
lib/public/components/common/form/deleteButton.js
lib/public/views/QcFlags/ActiveColumns/qcFlagsActiveColumns.js
lib/public/views/QcFlags/ForDataPass/QcFlagsForDataPassOverviewPage.js
lib/public/views/QcFlags/details/qcFlagDetailsComponent.js
lib/server/services/qualityControlFlag/QcFlagService.js
test/api/qcFlags.test.js
test/lib/server/services/qualityControlFlag/QcFlagService.test.js
test/public/qcFlags/detailsForDataPass.test.js
test/public/qcFlags/detailsForSimulationPass.test.js

- Clicking on button to delete a flag actually mark it as deleted and remove its effective periods instead of removing it from database
- N/A
- Added `deleted` flag to QC flags in database

[O2B-1428] Discard flags instead of delete

---

lib/public/views/Runs/RunDetectorsSelectionModel.js
test/public/qcFlags/forDataPassCreation.test.js
test/public/runs/runsPerDataPass.overview.test.js

- Fixed de-selection of runs/detectors in runs per datapass
- N/A
- N/A

[O2B-1290] Fix run detectors selection in runs per data-pass overview

---

.eslintrc
lib/application.js
lib/server/kafka/AliEcsSynchronizer.js
lib/server/kafka/InfologgerKafkaLogCreator.js
test/public/defaults.js
test/public/runs/runsPerDataPass.overview.test.js

- N/A
- Kafka client will retry indefinitely when retriable errors occurs 
- N/A

[O2B-1412] Configure kafka to retry indefinitely

---

lib/database/migrations/v1/20250612095121-change-reconstructed-events-to-bigint.js
lib/database/models/dataPassVersion.js
lib/domain/entities/DataPassVersion.js
package-lock.json
package.json

- N/A
- `reconstructedEventsCount` is expected to be up to a value of 1e13, thus BIGINT definition is needed in SQL. 
-

[OGUI-1449] Use BIGINT for reconstructedEventsCount

---

lib/domain/dtos/GetAllEnvironmentsDto.js
lib/usecases/environment/GetAllEnvironmentsUseCase.js
test/api/environments.test.js
test/lib/usecases/environment/GetAllEnvironmentsUseCase.test.js

- GET API endpoint `environments` now allows for retrieving them filtered based on creation date time interval [from, to]
-
-

[O2B-1452] Add filter option by creation date interval for retrieving environments

---

lib/database/adapters/RunAdapter.js
lib/database/seeders/20220503120937-lhc-fills.js
test/public/lhcFills/detail.test.js
test/public/runs/detail.test.js

- NA
- Use colliding bunches from LHC_FILLS table if available
- NA

[O2B-1454] Use colliding bunches from LHC_FILLS if available
