AliceO2Group/Bookkeeping

lib/database/seeders/20200517151947-more-tags.js, lib/database/seeders/20200517152010-link-more-tags.js, lib/public/components/Filters/index.js, lib/public/views/Logs/Details/page.js, lib/public/views/Logs/Logs.js, test/public/logs/overview.test.js
https://alice.its.cern.ch/jira/browse/O2B-267
=> feat: Added possibility to show more or less filters

lib/public/app.css, lib/public/components/Filters/index.js, lib/public/components/PageSelector/index.js, lib/public/components/Pagination/amountSelector.js, lib/public/components/Pagination/index.js, lib/public/components/Pagination/pageSelector.js, lib/public/components/Table/index.js, lib/public/views/Logs/Logs.js, lib/public/views/Logs/Overview/index.js, test/public/logs/overview.test.js
https://alice.its.cern.ch/jira/browse/O2B-250
TODO:
- Make sure tag filters aren't reset by the pagination (another ticket?)
=> Log overview pagination

lib/public/views/Logs/Create/index.js, lib/public/views/Logs/Details/index.js, lib/public/views/Logs/Logs.js, lib/public/views/Logs/Overview/index.js, test/public/logs/detail.test.js, test/public/logs/overview.test.js
https://alice.its.cern.ch/jira/browse/O2B-303
=> RemoteData support for the Logs model

lib/public/utilities/scrollTo.js, lib/public/views/Logs/Details/index.js, test/public/logs/overview.test.js
Fixed a bug with the autoscrolling on longer threads with long replies
=> fix: Fix autoscrolling not completely going down on longer threads

lib/public/app.css, lib/public/components/Filters/index.js, lib/public/views/Logs/Logs.js, lib/public/views/Logs/Overview/index.js, test/public/logs/overview.test.js
https://alice.its.cern.ch/jira/browse/O2B-285
=> Restore filtering by tags

lib/public/components/Post/index.js
https://alice.its.cern.ch/jira/browse/O2B-335
=> Prevented run numbers overflowing beyond the log details table

lib/domain/dtos/GetAllLogsDto.js, lib/public/components/Filters/author.js, lib/public/components/Filters/created.js, lib/public/components/Filters/title.js, lib/public/components/NavBar/index.js, lib/public/components/Table/rows.js, lib/public/views/Logs/ActiveColumns/index.js, lib/public/views/Logs/Logs.js, test/e2e/logs.test.js, test/public/logs/create.test.js, test/public/logs/overview.test.js
https://alice.its.cern.ch/jira/browse/O2B-336
=> Improved Safari compatibility

lib/database/utilities/QueryBuilder.js, lib/domain/dtos/GetAllLogsDto.js, lib/public/app.css, lib/public/components/Filters/index.js, lib/public/components/Table/headers.js, lib/public/components/Table/index.js, lib/public/components/Table/rows.js, lib/public/views/Logs/ActiveColumns/index.js, lib/public/views/Logs/Logs.js, lib/public/views/Logs/Overview/index.js, lib/public/views/Runs/Overview/index.js, lib/public/views/Subsystems/Overview/index.js, lib/public/views/Tags/Overview/index.js, lib/usecases/log/GetAllLogsUseCase.js, spec/openapi-source.yaml, spec/openapi.yaml, test/e2e/logs.test.js, test/public/logs/overview.test.js
https://alice.its.cern.ch/jira/browse/O2B-217
=> Log overview sorting

lib/public/Model.js, lib/public/app.css, lib/public/components/NavBar/index.js, lib/public/components/Post/index.js, lib/public/view.js, lib/public/views/Logs/Create/index.js, lib/public/views/Logs/Details/index.js, lib/public/views/Logs/Logs.js, lib/public/views/Logs/Overview/index.js, lib/public/views/Runs/Details/index.js, lib/public/views/Runs/Overview/index.js, lib/public/views/Runs/Runs.js, lib/public/views/Subsystems/Details/index.js, lib/public/views/Subsystems/Overview/index.js, lib/public/views/Tags/Details/index.js, lib/public/views/Tags/Overview/index.js, lib/public/views/Tags/Tags.js, test/public/logs/create.test.js, test/public/logs/detail.test.js, test/public/logs/overview.test.js, test/public/runs/detail.test.js, test/public/runs/overview.test.js, test/public/subsystems/detail.test.js, test/public/subsystems/overview.test.js, test/public/tags/create.test.js, test/public/tags/detail.test.js, test/public/tags/overview.test.js
https://alice.its.cern.ch/jira/browse/O2B-344
=> Update navbar header

lib/domain/dtos/CreateAttachmentDto.js, lib/domain/dtos/CreateLogDto.js, lib/domain/dtos/CreateSubsystemDto.js, lib/domain/dtos/CreateTagDto.js, lib/domain/dtos/EntityIdDto.js, lib/domain/dtos/FileDto.js, lib/domain/dtos/GetAllFlpsDto.js, lib/domain/dtos/GetAllLogAttachmentsDto.js, lib/domain/dtos/GetAllLogsDto.js, lib/domain/dtos/GetAllRunsDto.js, lib/domain/dtos/GetAllSubsystemsDto.js, lib/domain/dtos/GetAllTagsDto.js, lib/domain/dtos/GetAttachmentDto.js, lib/domain/dtos/GetFlpDto.js, lib/domain/dtos/GetLogAttachmentDto.js, lib/domain/dtos/GetLogDto.js, lib/domain/dtos/GetRunDto.js, lib/domain/dtos/GetSubsystemDto.js, lib/domain/dtos/GetTagDto.js, lib/domain/dtos/PaginationDto.js, package-lock.json, package.json
joi is part of the hapi ecosystem and was designed to work seamlessly with the [hapi web framework](https://hapi.dev/) and its other components (but works great on its own or with other frameworks). If you are using a different web framework and find this module useful, check out [hapi](https://hapi.dev/) – they work even better together.
=> Update: Renamed @hapi/joi to joi

lib/public/app.css, lib/public/components/Pagination/amountSelector.js, lib/public/views/Flps/Flps.js, lib/public/views/Flps/Overview/index.js, lib/public/views/Logs/Logs.js, lib/public/views/Logs/Overview/index.js, lib/public/views/Runs/Overview/index.js, lib/public/views/Runs/Runs.js, test/.eslintrc, test/public/runs/overview.test.js
Adds an input field as option in a pagination dropdown. User will be able to type from 1 to 100 (as defined in controllers).
=> feat(Pagination): add option with input to amountSelector

lib/public/views/About/Overview/index.js, package.json
=> updated npm version

lib/database/adapters/FlpRunsAdapter.js, lib/database/tables/flpruns.js, lib/domain/dtos/CreateFlpDto.js, lib/public/components/FlpRun/index.js, lib/public/views/Flps/Details/index.js, lib/usecases/flp/CreateFlpUseCase.js, lib/usecases/flp/GetFlpUseCase.js, test/public/flps/detail.test.js, test/public/flps/index.js, test/usecases/flp/CreateFlpUseCase.test.js, test/usecases/flp/GetAllFlpsUseCase.test.js, test/usecases/flp/index.js, test/usecases/index.js
Changed so that the foreign_key relation is correct in flp_runs
=> Added runs to flps

CHANGELOG.md, lib/public/views/About/Overview/index.js, package-lock.json, package.json
bump patch version number so 0.17.3
=> New npm version

lib/public/Model.js, lib/public/views/Tags/Tags.js
=> Added an extra function that grabs all tags

Dockerfile, lib/public/views/Runs/Runs.js
* Updates Dockerfile to use lowercase for labels
* Removes forgotten console statement, thus fixing 2 lint issues
=> [O2B-457] Dockerfile updates and lint fixes

lib/public/views/Tags/Details/index.js, test/public/tags/detail.test.js
Tested on own desktop within browser and ran local chai tests without issues.
=> [O2B-447] Removed main panel and modified router params to point to logs panel.

lib/public/views/Runs/Details/index.js, test/public/flps/detail.test.js, test/public/logs/detail.test.js, test/public/runs/detail.test.js
…wn by default. Modified tests, but errors are still showing. The test errors are still there but the functionality is correct. I couldn't test it all the way because of certain 500 internal server errors
=> [O2B-438] Moved main logs table to the right of the screen. 

lib/public/views/Tags/Overview/index.js, package-lock.json, package.json, spec/convert.js, spec/openapi-source.yaml, spec/openapi.yaml, test/openapi.test.js
Migrate to  `js-yaml` v4 and update openapi files
=> [O2B-459] Migrate to js-yaml v4

lib/config/database.js, lib/config/jwt.js, lib/config/openid.js
=> [O2B-469] Update configs with in-line condition

lib/application.js, lib/main.js, test/index.js
Added periodically connection to database (for now every five seconds)
=> [O2B-446] NodeJS server process shouldn't fail if database is not available

CHANGELOG.md
=> Update changelog following release of 0.19

Dockerfile, docs/DOCKER.md
=> [O2B-475] Update ca-certificates

lib/public/components/RunDetail/index.js, lib/public/components/Table/rows.js, lib/public/views/Runs/ActiveColumns/index.js, test/public/runs/detail.test.js
Displays the run quality in r`un-overview` and `run-details` for a run or `-` if there is no value.
Hides from `run-overview` the `TRG start/stop values` as currently these are the same as `RUN start/stop`
=> [OGUI-482] Display run quality column on run-overview and run-details

lib/public/components/RunDetail/index.js, lib/public/views/Runs/Details/editTagsPanel.js, lib/public/views/Runs/Details/index.js, lib/public/views/Runs/Runs.js, test/public/runs/detail.test.js
Adds new Edit Mode for `Run-Details` page which allows the user to get displayed widgets for editing:
* tags
* run-quality (toggle is represented by an html select tag)
Add run-quality field to both `Run-Details` and `Run-Overview` pages and for details add them as badges
=> [O2B-484] Add Edit Mode and quality field to runs

lib/domain/dtos/GetAllRunsDto.js, lib/public/components/Filters/RunsFilter/runQuality.js, lib/public/views/Runs/ActiveColumns/index.js, lib/public/views/Runs/Runs.js, lib/usecases/run/GetAllRunsUseCase.js
In the Filters options of Run-Overview page, adds a new filter: `runQuality` which expects a string and filters the runs by it
=> [O2B-486] Add RunQuality as filter option to RunOverview

lib/public/components/Post/index.js, lib/public/components/PostCollapsed/index.js, lib/public/components/RunDetail/index.js
=> [O2B-487] Add check for null values before attempt to display

CHANGELOG.md, docs/DEVELOPMENT.md, docs/data-model.md, lib/public/views/About/Overview/index.js, lib/server/middleware/multer.middleware.js, package-lock.json, package.json
* Adds option to use location for storing attachments as configurable parameter
=> [O2B-491] Configurable attachment location

CHANGELOG.md, lib/public/views/About/Overview/index.js
* Adds option to Email updates on log creation;
=> Release 0.23.0

lib/public/views/Logs/Details/index.js, test/public/logs/detail.test.js
If a Log-Detail view displays a log with no children, then log should show by default all information
=> [O2B-479] Dispaly log details if it has no children

lib/usecases/user/CreateOrUpdateUser.js
Add to the user middleware the `username` and `access`
=> [O2B-537] Return all information on user from session

lib/domain/dtos/GetAllLogsDto.js, lib/domain/dtos/GetAllRunsDto.js, lib/server/controllers/logs.controller.js, lib/server/controllers/runs.controller.js, lib/server/utilities/fromToValidator.js, lib/server/utilities/index.js, test/e2e/index.js, test/e2e/runs.test.js
=> [O2B-540] JOI validation caches dates

spec/openapi-source.yaml, spec/openapi.yaml, test/e2e/runs.test.js
=> [O2B-543] - Fix skipped tests for filter

lib/public/components/Filters/RunsFilter/nDetectors.js, lib/public/components/Filters/RunsFilter/nFlps.js
If negative values are filled in the field will be reset to an empty value.
=> [O2B-555] FLP/Detector number fields in Run Filters cannot be negative

database/configuration/my.cnf, lib/database/adapters/EnvironmentAdapter.js, lib/database/adapters/RunAdapter.js, lib/database/adapters/index.js, lib/database/migrations/20220404093143-create-environments-table.js, lib/database/migrations/20220412121531-create-env-id-for-runs.js, lib/database/models/environment.js, lib/database/models/index.js, lib/database/models/run.js, lib/database/repositories/EnvironmentRepository.js, lib/database/repositories/index.js, lib/database/seeders/20200713103855-runs.js, lib/database/seeders/20220412122043-environments.js
Implemented and updated the environment/run tables, seeders, adapters, repositories.
=> [O2B-526] New environment database model

lib/public/views/Envs/ActiveColumns/index.js
=> [O2B-527] ToredownAt removed

database/configuration/my.cnf, docs/DEVELOPMENT.md, docs/data-model.md, lib/database/adapters/EnvironmentAdapter.js, lib/database/adapters/EorReasonAdapter.js, lib/database/adapters/index.js, lib/database/migrations/20220513075839-crete-eor-reason-table.js, lib/database/models/eorreason.js, lib/database/models/index.js, lib/database/repositories/EorReasonRepository.js, lib/database/repositories/index.js, lib/database/seeders/20220412122043-environments.js, lib/database/seeders/20220513083459-eor-reason.js
PR which:
* Creates a table for `eor_reasons`
* Adds model, adapter, repository needed for eor reasons
* Adds migration file and seeder file for testing purposes
* Updates `data-model.md` files
* Adds copyrights to missing environment ones
=> [O2B-564] Adds End of Run Reason table, model, adapters

Dockerfile
Updated FreeType to stop the dev/test suite from crashing.
=> [O2B-572] Update freetype

lib/usecases/lhcFill/GetAllLhcFillsUseCase.js
Lhc fills within the overview are now in descending order
=> [O2B-583] Lhc overview descending sort on fill number

lib/public/views/LhcFills/LhcFills.js, test/public/lhcFills/overview.test.js
=> [O2B-580] Fixed the lhc fills infinite mode

lib/public/components/NavBar/index.js, lib/public/components/RunDetail/index.js, lib/public/components/lhcFillsDetail/index.js, lib/public/views/LhcFills/ActiveColumns/index.js, test/public/runs/detail.test.js
As per the RC feedback:
* the `LHC` and `ALICE` should always be displayed in capitals
* `LHC Id` table header should be renamed to `Fill Number`
* EOR reasons - category, sub-category and descriptions should be displayed with `-` as separator
=> [O2B-588] Acronysms fixes and eor visuals improvements

lib/public/views/Runs/Details/index.js, test/public/runs/detail.test.js
=> [02B-546] Edit Run button admin validation frontend

lib/domain/dtos/GetAllRunsDto.js, lib/public/components/Filters/RunsFilter/runQuality.js, lib/public/components/Filters/RunsFilter/tags.js, lib/public/views/Runs/Runs.js, lib/usecases/run/GetAllRunsUseCase.js, test/e2e/runs.test.js, test/public/defaults.js, test/public/runs/overview.test.js, test/usecases/run/GetAllRunsUseCase.test.js
=> [O2B-512] Filter run qualities using checkboxes

lib/domain/dtos/GetAllTagsDto.js, lib/public/app.css, lib/public/components/Table/headers.js, lib/public/views/Tags/ActiveColumns/index.js, lib/public/views/Tags/Tags.js, lib/usecases/tag/GetAllTagsUseCase.js, test/e2e/tags.test.js, test/public/tags/overview.test.js, test/usecases/tag/GetAllTagsUseCase.test.js
=> [O2B-581] Add searchbox on tag name in tag overview

lib/database/seeders/20200508094502-logs.js, lib/database/seeders/20200511151016-log-tags.js, lib/database/seeders/20220412122043-environments.js, lib/public/views/Envs/ActiveColumns/index.js, lib/public/views/LhcFills/ActiveColumns/index.js, lib/public/views/Logs/ActiveColumns/index.js, test/public/envs/overview.test.js, test/public/lhcFills/overview.test.js, test/public/logs/create.test.js, test/public/logs/overview.test.js
=> [O2B-582] Add balloon on some overview pages

lib/database/utilities/QueryBuilder.js, lib/domain/dtos/GetAllRunsDto.js, lib/public/components/Filters/RunsFilter/nDetectors.js, lib/public/components/Filters/RunsFilter/nFlps.js, lib/public/components/Filters/components/amountFilter.js, lib/public/components/Filters/components/comparisonOperatorFilter.js, lib/public/components/Table/rows.js, lib/public/views/Runs/ActiveColumns/index.js, lib/public/views/Runs/Runs.js, lib/server/controllers/runs.controller.js, lib/usecases/run/GetAllRunsUseCase.js, test/e2e/runs.test.js, test/public/runs/overview.test.js, test/testUtilities/catchAsyncError.js, test/usecases/run/GetAllRunsUseCase.test.js
=> [O2B-511] Run filters should accept operators

.github/pull_request_template.md, CHANGELOG.md, lib/public/views/About/Overview/index.js, package-lock.json, package.json
=> Adding release notes 0.30.0

lib/database/utilities/QueryBuilder.js, lib/domain/dtos/GetAllRunsDto.js, lib/usecases/run/GetAllRunsUseCase.js, test/e2e/runs.test.js, test/usecases/run/GetAllRunsUseCase.test.js
=> [O2B-600] Api run should accept duration filter

lib/public/components/Post/index.js, lib/public/components/RunDetail/index.js, lib/public/components/TagDetail/index.js, lib/public/components/lhcFillsDetail/index.js, lib/public/utilities/formatTimestamp.js, lib/public/utilities/pick.js, lib/public/views/Envs/ActiveColumns/index.js, lib/public/views/LhcFills/ActiveColumns/index.js, lib/public/views/Logs/ActiveColumns/index.js, lib/public/views/Logs/Overview/index.js, lib/public/views/Runs/ActiveColumns/index.js, lib/public/views/Runs/ActiveColumnsLogs/index.js, lib/public/views/Runs/Overview/index.js, lib/public/views/Tags/ActiveColumns/index.js
=> [O2B-609] Factorize dates and timestamp displays

lib/public/components/Filters/RunsFilter/durationFilter.js, lib/public/components/Filters/components/amountFilter.js, lib/public/views/Runs/ActiveColumns/index.js, lib/public/views/Runs/Runs.js, test/public/runs/overview.test.js
=> [O2B-601] Add run duration column and filter

lib/public/components/Table/headers.js, lib/public/utilities/remoteDataFromResponse.js, lib/public/views/Tags/ActiveColumns/index.js, lib/public/views/Tags/Overview/TagsOverviewModel.js, lib/public/views/Tags/Overview/index.js, lib/public/views/Tags/Tags.js
=> [O2B-615] Fix persistent tags filtering

CHANGELOG.md, database/CHANGELOG.md, lib/public/views/About/Overview/index.js, lib/public/views/Runs/Details/index.js, package-lock.json, package.json
=> Release 0.31.0

lib/public/utilities/parseFetchResponse.js, lib/public/views/Runs/Runs.js
=> [O2B-610] Fix runs infinite mode

lib/public/components/Filters/LogsFilter/created.js, lib/public/components/Filters/RunsFilter/o2start.js, lib/public/components/Filters/RunsFilter/o2stop.js, lib/public/views/Logs/Logs.js, lib/public/views/Runs/Runs.js
=> [O2B-636] Fix debounced filtering

lib/public/components/Detail/index.js, lib/public/components/RunDetail/index.js, lib/public/components/lhcFillsDetail/index.js, lib/public/utilities/formatTimestamp.js, lib/public/views/Runs/ActiveColumns/index.js, lib/public/views/Runs/formatRunDuration.js
=> [O2B-620] Add run duration to details page + bug fixes

lib/public/utilities/debounce.js, lib/public/views/Logs/Logs.js, lib/public/views/Runs/Runs.js, test/public/logs/overview.test.js, test/public/runs/overview.test.js
=> [O2B-523] Fix filtering in infinite mode for runs and logs

lib/public/views/Runs/formatRunDuration.js, test/public/runs/overview.test.js
=> [O2B-634] Display as "unknown" duration above 48 hours

.github/CODEOWNERS
=> Fix syntax of codeowners

lib/public/views/Runs/formatRunDuration.js
=> [O2B-647] Fix run duration displaying UNKNOWN above 48h

lib/domain/dtos/GetAllRunsDto.js, lib/public/components/Filters/RunsFilter/fillNumbers.js, lib/public/views/Runs/ActiveColumns/index.js, lib/public/views/Runs/Runs.js, lib/usecases/run/GetAllRunsUseCase.js, test/public/runs/overview.test.js, test/usecases/run/GetAllRunsUseCase.test.js
=> [O2B-648] Fill number information on run overview

CHANGELOG.md, lib/public/views/About/Overview/index.js, package-lock.json, package.json
=> Add release notes for 0.33.0

lib/public/components/Table/SortModel.js, lib/public/components/Table/headers.js, lib/public/components/Table/index.js, lib/public/components/Table/rows.js, lib/public/views/About/Overview/index.js, lib/public/views/Envs/Overview/index.js, lib/public/views/Flps/Overview/index.js, lib/public/views/Home/Overview/index.js, lib/public/views/LhcFills/Overview/index.js, lib/public/views/Logs/Logs.js, lib/public/views/Logs/Overview/index.js, lib/public/views/Runs/Details/index.js, lib/public/views/Runs/Overview/index.js, lib/public/views/Subsystems/Details/index.js, lib/public/views/Subsystems/Overview/index.js, lib/public/views/Tags/ActiveColumns/index.js, lib/public/views/Tags/Details/index.js, lib/public/views/Tags/Overview/index.js, test/public/logs/create.test.js, test/public/logs/overview.test.js
* Extracted sorting of logs in a sub-model and fixed preview bug
* Remove any dependency on model from table component
=> [O2B-619] Refactor table to be model-independent

lib/public/Model.js, lib/public/views/Envs/Envs.js, lib/public/views/Envs/Overview/index.js, lib/public/views/Flps/Flps.js, lib/public/views/Flps/Overview/index.js, lib/public/views/Home/Overview/index.js, lib/public/views/LhcFills/Overview/index.js, lib/public/views/Logs/Overview/index.js, lib/public/views/Runs/Details/index.js, lib/public/views/Runs/Overview/index.js, lib/public/views/Subsystems/Details/index.js, lib/public/views/Subsystems/Overview/index.js, lib/public/views/Tags/Details/index.js, lib/public/views/Tags/Overview/TagsOverviewModel.js, lib/public/views/Tags/Overview/index.js, lib/usecases/flp/GetAllFlpsUseCase.js, lib/utilities/setPromiseTimeout.js, test/public/tags/overview.test.js
=> [O2B-619] Inform user when table data is loading

CHANGELOG.md, lib/public/views/About/Overview/index.js, package-lock.json, package.json
=> Add release notes for 0.34.0

CHANGELOG.md, lib/domain/dtos/GetAllRunsDto.js, lib/public/components/Filters/RunsFilter/nEpns.js, lib/public/components/RunDetail/index.js, lib/public/views/Runs/ActiveColumns/runsActiveColumns.js, lib/public/views/Runs/Runs.js, lib/usecases/run/GetAllRunsUseCase.js, test/e2e/runs.test.js, test/public/runs/overview.test.js
Implemented the number of EPNs in the overview/details page. It can now also be filtered and exported.
=> [O2B-654] Epns UI

database/CHANGELOG.md, docs/data-model.md, go-api-client/Example.go, lib/database/seeders/20200713103855-runs.js, lib/public/components/Filters/RunsFilter/lhcPeriod.js, lib/public/components/RunDetail/index.js, test/e2e/runs.test.js, test/public/runs/overview.test.js, test/usecases/run/EndRunUseCase.test.js, test/usecases/run/GetAllRunsUseCase.test.js, test/usecases/run/GetRunUseCase.test.js
Received feedback that we should try to use the conventions for placeholders and labels as much as possible. 
PR updates the remaining labels with such issues
=> [O2B-671] Update labels and placeholders as per conventions

CHANGELOG.md, lib/database/seeders/20200511151010-tags.js, lib/database/seeders/20200713103855-runs.js, lib/database/seeders/20220603150752-run-tag.js, lib/public/app.css, lib/public/services/run/extractRunStatistics.js, lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js, lib/server/controllers/lhcFill.controller.js, lib/usecases/lhcFill/GetLhcFillUseCase.js, test/e2e/runs.test.js, test/e2e/tags.test.js, test/public/lhcFills/detail.test.js, test/public/tags/overview.test.js, test/usecases/run/GetAllRunsUseCase.test.js, test/usecases/tag/GetAllTagsUseCase.test.js
=> [O2B-651] Add LHC fills statistics

lib/public/Model.js
=> [O2B-678] Debounce render after window resize

CHANGELOG.md, lib/domain/dtos/CreateTagDto.js, lib/public/views/Tags/Create/index.js, test/e2e/tags.test.js
=> [O2B-646] Allow tags of 2 characters

lib/public/components/Detail/detailsList.js, lib/public/views/Runs/Details/lhcFillPanel.js, lib/public/views/Runs/Runs.js
=> [O2B-683] Fix run details page when there is no LHC fill

CHANGELOG.md, lib/public/app.css, lib/public/components/NavBar/index.js, lib/public/utilities/frontLink.js
=> [O2B-665] Main tabs are links and no buttons

CHANGELOG.md, lib/config/httpConfig.js, lib/domain/dtos/CreateLogDto.js, lib/server/controllers/logs.controller.js, lib/server/controllers/tags.controller.js, lib/usecases/log/CreateLogUseCase.js
=> [O2B-682] Send log creation from usecase not controller

CHANGELOG.md, docker-compose.dev.yml, lib/database/index.js, lib/database/repositories/Repository.js, lib/database/seeders/20200511151010-tags.js, lib/database/utilities/TransactionHelper.js, lib/public/components/Detail/detailsList.js, lib/usecases/lhcFill/checkLhcFill.js, lib/usecases/log/CreateLogUseCase.js, lib/usecases/log/GetAllLogsUseCase.js, lib/usecases/run/GetAllRunsUseCase.js, lib/usecases/run/UpdateRunUseCase.js, lib/usecases/run/getRunOrFail.js, lib/usecases/tag/getAllTagsByTextOrFail.js, lib/usecases/tag/getTagsByTextUseCase.js, lib/usecases/tag/index.js, test/public/home/overview.test.js, test/public/logs/create.test.js, test/public/logs/overview.test.js, test/usecases/run/UpdateRunUseCase.test.js, test/usecases/tag/GetAllTagsUseCase.test.js
=> [O2B-642] Run quality change should create a log

lib/public/services/lhcFill/computeLhcFillStatistics.js
=> [O2B-687] Fix negative LHC before first run duration

lib/usecases/log/CreateLogUseCase.js
=> [O2B-686] Fix log notification for auto-generated logs

CHANGELOG.md, lib/usecases/environment/GetAllEnvironmentsUseCase.js
=> [O2B-611] Fix environment overview slow loading time

CHANGELOG.md, lib/public/view.js
=> [O2B-700] Fix several table display when row ids match

CHANGELOG.md, lib/database/repositories/qbHelpers/lhcFill/physicsRunsIncludeExpression.js, lib/usecases/lhcFill/GetAllLhcFillsUseCase.js, lib/usecases/lhcFill/GetLhcFillUseCase.js, test/usecases/lhcFill/GetLhcFillUseCase.test.js
=> [O2B-695] Restrict LHC fills' runs to physics only

CHANGELOG.md, lib/public/views/LhcFills/Detail/LhcFillDetailsPage.js
=> [O2B-701] Fix LHC fill detail onremove

CHANGELOG.md, lib/public/views/Logs/Details/index.js, lib/public/views/Logs/Logs.js
=> [O2B-702] Fix log display cleanup

CHANGELOG.md, lib/public/views/Envs/Envs.js, test/public/envs/overview.test.js
=> [O2B-702] Fix environment pagination

CHANGELOG.md, lib/public/components/RunDetail/index.js
=> [O2B-672] Add run definition on run details

CHANGELOG.md, lib/public/components/Filters/LogsFilter/author.js, lib/public/components/Filters/LogsFilter/title.js, lib/public/components/Filters/common/filters/FilterInputModel.js, lib/public/views/Logs/Logs.js
=> [O2B-716] Fix log filtering whitespaces removal

lib/public/views/Logs/Create/LogCreationModel.js
=> [O2B-637] Fix log creation error handling

lib/public/components/common/markdown/markdown.js
=> [O2B-637] Fix markdown auto size

lib/public/views/Runs/formatRunDuration.js
Updated wrong if condition to alter properly when trigger is not defined.  Can be tested by putting a debug  before the if statement and change `timeTrgStart` to null and `timeO2Start` to `timeO2Start = Date.now()`.
=> [O2B-732] Duration time showing unknown when running

CHANGELOG.md, lib/public/components/RunDetail/index.js, lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
=> [O2B-730] Runs home to start stop

CHANGELOG.md, lib/public/views/Runs/Runs.js
=> [O2B-733] Fix run overview active filters

CHANGELOG.md, lib/public/views/Logs/Overview/index.js, lib/public/views/Runs/Overview/index.js
=> [O2B-727] Fix infinite requests when going from runs/logs to homepage

CHANGELOG.md, lib/public/views/Logs/Logs.js, lib/public/views/Runs/Runs.js
=> [O2B-734] Display spinner when log overview is loading

CHANGELOG.md, lib/database/seeders/20200713103855-runs.js, lib/domain/dtos/GetAllRunsDto.js, lib/public/components/Filters/RunsFilter/definitionFilter.js, lib/public/views/Runs/Runs.js, lib/services/getRunDefinition.js, lib/usecases/run/GetAllRunsUseCase.js, test/e2e/runs.test.js, test/public/runs/overview.test.js, test/usecases/lhcFill/GetLhcFillUseCase.test.js, test/usecases/run/GetAllRunsUseCase.test.js
=> [O2B-724] Add CALIBRATION to run definition

CHANGELOG.md, docker-compose.test.yml, lib/config/apiConfig.js, lib/config/index.js, lib/public/components/Pagination/amountSelector.js, lib/server/controllers/environments.controller.js, lib/server/controllers/flps.controller.js, lib/server/controllers/lhcFill.controller.js, lib/server/controllers/logs.controller.js, lib/server/controllers/runTypes.controller.js, lib/server/controllers/runs.controller.js, lib/server/controllers/subsystems.controller.js, lib/usecases/environment/GetAllEnvironmentsUseCase.js, lib/usecases/flp/GetAllFlpsUseCase.js, lib/usecases/lhcFill/GetAllLhcFillsUseCase.js, lib/usecases/log/GetAllLogsUseCase.js, lib/usecases/run/GetAllRunsUseCase.js, lib/usecases/runType/GetAllRunTypesUseCase.js, lib/usecases/subsystem/GetAllSubsystemsUseCase.js, test/public/envs/overview.test.js, test/public/lhcFills/overview.test.js, test/public/runs/overview.test.js
=> [O2B-650] Increase pagination limits to 1k (5k on the API)

lib/database/adapters/RunAdapter.js, test/e2e/runs.test.js, test/usecases/run/StartRunUseCase.test.js
- Fixed the bug which did not linked the run to an environment properly
=> [O2B-744] Fix environment's run link when creating run

docs/RUN_DEFINITIONS.md
- DOCs added for sharing run definitions with users;
=> Add documentation on run definitions

lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
- Runs in the home page are noticeably smaller
=> [O2B-751] Start stop runs now inline

lib/public/components/Pagination/PaginationModel.js, lib/public/components/Pagination/amountSelector.js, lib/public/views/Envs/Envs.js, lib/public/views/Flps/Flps.js, lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js, lib/public/views/Logs/Logs.js, lib/public/views/Runs/Runs.js
- Fixed several bugs related to the infinite scroll
=> [O2B-743] Always start infinite scroll from the first item

lib/server/services/run/RunService.js, lib/server/services/run/updateRun.js, lib/server/services/user/UserService.js, lib/server/services/user/getUser.js, lib/server/services/user/getUserOrFail.js, lib/usecases/run/UpdateRunUseCase.js, test/usecases/run/UpdateRunUseCase.test.js
- Log only run quality change from good to bad and the other way around
- Add information to the log created when run quality change such as user and date
=> [O2B-749] Improve run quality update logging

.github/pull_request_template.md, .github/workflows/bookkeeping.yml, .github/workflows/docker.yml, .github/workflows/openapi.yml
- Update Github CI ubuntu from 18.04 to latest
- Fix typo in PR template
=> Update CI ubuntu base + fix PR template typo

lib/public/components/Pagination/PaginationModel.js, lib/public/components/Pagination/amountSelector.js, lib/public/components/Pagination/paginationComponent.js, lib/public/views/Envs/Envs.js, lib/public/views/Flps/Flps.js, lib/public/views/LhcFills/Overview/LhcFillsOverviewModel.js, lib/public/views/Logs/Logs.js, lib/public/views/Runs/Runs.js, test/public/envs/overview.test.js, test/public/flps/overview.test.js, test/public/lhcFills/overview.test.js, test/public/logs/overview.test.js, test/public/runs/overview.test.js
- Added an items counter at the bottom of overview pages
=> [O2B-740] Add total items counter at the bottom of the page

package.json
Fixes the delivery bug where generated npm package was missing the proto directory and its content
=> [O2B-772] Add proto to npm package

lib/database/migrations/20221010120629-convert-run-detectors-to-separate-table.js
- Fixed the detectors table fill migration to handle runs with empty or null detectors list
Fix the detectors table fill migration by adding a transaction and handling properly the runs without detectors
=> [O2B-773] Fix detectors migration

lib/database/models/typedefs/SequelizeRunDetector.js, lib/public/components/RunDetail/index.js, lib/server/services/runDetector/updateRunDetector.js, lib/usecases/run/UpdateRunUseCase.js, test/e2e/runs.test.js, test/public/defaults.js, test/public/runs/detail.test.js, test/public/runs/overview.test.js, test/usecases/run/GetRunUseCase.test.js, test/usecases/run/UpdateRunUseCase.test.js
- Tests were added for the run detectors quality edition
=> [O2B-782] Add test to run detector quality edition

lib/database/adapters/RunAdapter.js, test/usecases/run/GetRunUseCase.test.js
- Run's detectors are sorted alphabetically
=> [O2B-782] Sort detectors alphabetically

lib/server/services/run/updateRun.js, lib/server/services/tag/getTagsByText.js, test/public/defaults.js, test/public/home/overview.test.js, test/public/logs/overview.test.js, test/usecases/run/UpdateRunUseCase.test.js
- A log is created when run quality change, and DPG and RC tags are added for good<->bad quality change only
=> [O2B-788] Log quality change in any case

lib/server/services/log/createLog.js
- No more errors when ECS creates logs through gRPC
=> [O2B-789] Fix log creation by anonymous user

lib/public/view.js
- Fixed bug where text selection was canceled on mouse up after page switch
=> [O2B-770] Fix text selection after router navigation

lib/database/migrations/20221116132910-run-detector-quality-update.js
=> [O2B-762] Fix migration for null detectors quality

lib/public/app.css, lib/public/components/RunDetail/index.js, test/public/runs/detail.test.js
- An icon has been added to outline the detector's quality
=> [O2B-791] Add icons to outline run detectors quality

.dockerignore, docker-compose.dev.yml
=> [O2B-792] Remove spec volume from docker compose

lib/server/controllers/gRPC/GRPCFlpController.js, proto/flp.proto
- FLP proto creation request expect a `hostname` instead of `hostName`
=> [O2B-798] Rename hostName to hostname in flp proto

docs/backend-architecture.md
- A general architecture documentation has been added
=> [O2B-677] Add documentation

lib/public/index.html, lib/public/index.js, package-lock.json, package.json
- none
- migration to v2 of web-ui framework which improves security following IT recommendations
- none
=> [OGUI-1303] Migrate to v2 web-ui framework

Dockerfile
- Upgrade git from `2.36.3-r0` to `2.36.4-r0` in Dockerfile
=> Fix git version in CI

lib/public/components/RunDetail/index.js
- Prevent detectors list in run display to wrap if there is enough space
=> [O2B-802] Fix detectors items wrap

lib/utilities/buildUrl.js, test/lib/utilities/buildUrl.test.js, test/public/about/overview.test.js, test/public/defaults.js, test/public/envs/overview.test.js, test/public/flps/detail.test.js, test/public/flps/overview.test.js, test/public/home/overview.test.js, test/public/lhcFills/detail.test.js, test/public/lhcFills/overview.test.js, test/public/logs/create.test.js, test/public/logs/detail.test.js, test/public/logs/overview.test.js, test/public/runs/detail.test.js, test/public/runs/overview.test.js, test/public/subsystems/detail.test.js, test/public/subsystems/overview.test.js, test/public/tags/create.test.js, test/public/tags/detail.test.js, test/public/tags/overview.test.js
- goToPage test utility has been improved and must be used exclusively
- Puppeteer should less fail randomly now
=> [O2B-807] Authenticate puppeteer navigation to avoid connection aborted

lib/server/controllers/gRPC/GRPCFlpRoleController.js, lib/server/services/flp/FlpRoleService.js, lib/server/services/flp/getFlpRole.js, lib/server/services/flp/getFlpRoleOrFail.js, lib/server/services/flp/updateFlpRole.js, lib/usecases/flp/GetFlpUseCase.js, proto/flp.proto, test/lib/server/services/flpRole/FlpRoleService.test.js, test/lib/server/services/flpRole/index.js, test/lib/server/services/flpRole/updateFlpRole.test.js, test/public/runs/overview.test.js
- Add a gRPC endpoint to update FLP readout counters
=> [O2B-796] Add FLP update endpoint

lib/main.js
- Timeout for connection to the database has been increased
=> [O2B-811] Remove db connection retry timeout

cxx-client/README.md
- cxx API's documentation has been fixed
=> [O2B-677] Fix cxx client readme

.github/workflows/bookkeeping.yml, Dockerfile, docker-compose.coverage.yml
- Tests runs locally do not have the coverage report displayed anymore
=> [O2B-815] Separate tests from coverage

Dockerfile
- Packages used by the local docker stack has been upgraded to comply with alpine linux 3.17
=> [O2B-816] Update docker stack

lib/database/index.js
- Database connection is retried every 5 seconds on failing (before running migrations)
=> [O2B-811] Improve database connection retry

Dockerfile, lib/database/migrations/20230120160345-add-environment-history.js
- Data migration has been fixed to have the env history in the right orded
=> [O2B-813] Fix migration of existing data

lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
- Fixed the popover display of run duration warning
=> [O2B-771] Fix run duration popover

Dockerfile
- Docker dependencies has been updated
=> [O2B-831] Update git version in Dockerfile

lib/public/views/Runs/format/formatRunDuration.js, lib/public/views/Runs/format/formatRunEnd.js, lib/public/views/Runs/format/formatRunStart.js, test/public/runs/overview.test.js
- Runs overview columns do not overlap anymore on small screens
=> [O2B-833] Fix runs overview warning icon wrap

lib/public/views/Runs/format/formatRunDuration.js, lib/public/views/Runs/format/formatRunEnd.js, lib/public/views/Runs/format/formatRunStart.js
- Fixed the bug centering some run column's content
=> [O2B-833] Fix run columns centering

lib/public/Model.js, lib/public/components/Filters/common/TagFilterModel.js, lib/public/components/Filters/common/filters/tagFilter.js, lib/public/components/common/selection/SelectionModel.js, lib/public/components/common/selection/dropdown/SelectionDropdownModel.js, lib/public/components/common/selection/picker/PickerModel.js, lib/public/components/tag/TagPickerModel.js, lib/public/components/tag/TagSelectionDropdownModel.js, lib/public/components/tag/tagPicker.js, lib/public/services/tag/tagsProvider.js, lib/public/utilities/asRemoteData.js, lib/public/views/Logs/ActiveColumns/logsActiveColumns.js, lib/public/views/Logs/Create/LogCreationModel.js, lib/public/views/Logs/Create/LogCreationPage.js, lib/public/views/Logs/Create/logCreationComponent.js, lib/public/views/Logs/Logs.js, lib/public/views/Runs/ActiveColumns/runsActiveColumns.js, lib/public/views/Runs/Details/RunDetailsModel.js, lib/public/views/Runs/Details/editTagsPanel.js, lib/public/views/Runs/Runs.js, lib/public/views/Tags/Details/TagDetailsModel.js, lib/public/views/Tags/Tags.js, test/public/logs/overview.test.js, test/public/runs/overview.test.js
- Filtering on tags is now done using a dropdown tag picker
- Tags used in picker and dropdown now comes from a separate provider, not from model
=> [O2B-835] Use dropdown as tag filter

lib/domain/enums/BkpRoles.js, lib/server/WebUiServer.js, lib/server/controllers/tags.controller.js, lib/server/middleware/rbac.middleware.js, lib/server/routers/tags.router.js, test/lib/server/index.js, test/lib/server/middleware/index.js, test/lib/server/middleware/rbac.middleware.test.js
- A role based authorization control middleware is now available
=> [O2B-838] Create a role based access control middleware

lib/public/utilities/dateUtils.js, lib/public/utilities/formatting/formatTimestamp.js, lib/public/views/Runs/format/formatRunDuration.js, lib/public/views/Runs/format/formatRunEnd.js, lib/public/views/Runs/format/formatRunStart.js, test/public/runs/detail.test.js, test/public/runs/overview.test.js
- Optimized rows height in run overview
=> [O2B-833] Optimize warning icon space in runs overview

lib/server/services/eosReport/EosReportService.js, lib/server/services/log/LogService.js, lib/server/services/log/getLogsByUserInPeriod.js, lib/server/services/log/logIncludeClauseFromRelations.js, lib/utilities/Period.js, test/lib/server/services/log/getLogsByTagsInPeriod.test.js, test/lib/server/services/log/getLogsByUserInPeriod.test.js
- Added a function to fetch logs created by a user in a given period
=> [O2B-840] Add function to fetch logs by user

lib/server/services/eosReport/EosReportService.js, lib/server/services/log/getLogsByUserInPeriod.js, test/lib/server/services/eosReport/EosReportService.test.js, test/lib/server/services/eosReport/index.js, test/mocks/mock-eos-report.js
- EOS report now include user-created logs
=> [O2B-840] Add user-created log to report

lib/domain/dtos/eorReport/CreateEosReportDto.js, lib/public/Model.js, lib/public/app.css, lib/public/components/common/markdown/markdown.js, lib/public/view.js, lib/public/views/EosReport/EosReportModel.js, lib/public/views/EosReport/create/EosReportCreationModel.js, lib/public/views/EosReport/create/EosReportCreationPage.js, lib/public/views/EosReport/create/eosReportCreationComponent.js, lib/public/views/Logs/Overview/index.js, lib/server/WebUiServer.js, lib/server/controllers/eosReport.controller.js, lib/server/services/eosReport/formatEosReport.js, lib/server/services/eosReport/getShiftFromTimestamp.js, test/api/eosReport.test.js, test/mocks/mock-eos-report.js, test/public/defaults.js, test/public/eosReport/creation.test.js, test/public/eosReport/index.js
- A page to create end of shift report has been created
=> [O2B-841] Add EOS report creation page

lib/server/services/environment/EnvironmentService.js, lib/server/services/environment/environmentIncludeClauseFromRelations.js, lib/server/services/environment/getEnvironmentsInPeriod.js, test/lib/server/services/environment/getEnvironmentsInPeriod.test.js, test/lib/server/services/environment/index.js
- Added a function to fetch environments for a given period
=> [O2B-840] Add function to fetch environments in a given period

lib/server/controllers/eosReport.controller.js
- Fixed bug for shift extraction in EOS report controller
=> [O2B-840] Fix shift start extraction in EOS report controller

Dockerfile
- Updated chromium in dockerfile
=> [O2B-831] Update docker dependencies

lib/database/models/run.js, lib/database/models/typedefs/SequelizeRun.js, lib/server/services/environment/EnvironmentService.js, lib/server/services/environment/environmentIncludeClauseFromRelations.js, lib/server/services/environment/getEnvironmentsInPeriod.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js, lib/server/services/eosReport/formatEosReport.js, lib/server/services/log/getLogsByTagsInPeriod.js, lib/server/services/run/RunService.js, lib/server/services/run/runIncludeClauseFromRelations.js, test/api/eosReport.test.js, test/lib/server/services/environment/getEnvironmentsInPeriod.test.js, test/lib/server/services/eosReport/EosReportService.test.js, test/lib/server/services/eosReport/formatEosReport.test.js, test/mocks/mock-eos-report.js
- Completed the ECS EOS report
=> [O2B-840] Add ECS-specific data to EOS report

lib/server/services/shift/getShiftFromTimestamp.js, test/api/shift.test.js
- Make shift start at 000 milliseconds
- Fixed shift info fetch test
=> [O2B-850] Fix failing shift info test

docker-compose.dev.yml, lib/config/gRPCConfig.js, lib/config/httpConfig.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js, lib/server/services/eosReport/formatEosReport.js, lib/utilities/frontUrl.js, test/mocks/mock-eos-report.js
- EoS report now contains real links
=> [O2B-840] Make links real links

lib/domain/dtos/eorReport/CreateEosReportDto.js, lib/public/views/EosReport/create/eosReportCreationComponent.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/formatEosReport.js, test/mocks/mock-eos-report.js, test/public/eosReport/creation.test.js, test/public/index.js
- The LHC machine transitions can be filled in the EOS report
=> [O2B-840] Add LHC machine transitions

lib/public/utilities/dateUtils.js, lib/public/views/EosReport/create/eosReportCreationComponent.js, lib/server/services/eosReport/formatEosReport.js, lib/server/services/run/RunService.js, lib/server/services/shift/ShiftService.js, lib/server/services/shift/getShiftFromTimestamp.js, lib/server/utilities/formatServerDate.js, test/mocks/mock-eos-report.js
- EOS report form has been cleaned
=> [O2B-841] Polish EOS report form

lib/domain/dtos/eorReport/CreateEosReportDto.js, lib/public/views/EosReport/EosReportModel.js, lib/public/views/EosReport/create/EosReportCreationModel.js, lib/public/views/EosReport/create/ecs/eosFormEcsSpecificPart.js, lib/public/views/EosReport/create/eosReportCreationComponent.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js, test/mocks/mock-eos-report.js, test/public/eosReport/creation.test.js
- A comment can be added to each run in ECS EOS report
=> [O2B-841] Add run comments

lib/domain/dtos/eorReport/CreateEosReportDto.js, lib/public/views/EosReport/create/EosReportCreationModel.js, lib/public/views/EosReport/create/ecs/eosFormEcsSpecificPart.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js, test/mocks/mock-eos-report.js
- A comment can be added to environments without runs in ECS EOS report
=> [O2B-840] Add environment comments

lib/public/views/EosReport/create/ecs/eosFormEcsSpecificPart.js, lib/public/views/EosReport/create/eosReportCreationComponent.js
- EoS form links now opens in new tab
=> [O2B-841] Open EOS links in new tabs

lib/server/services/eosReport/EosReportService.js, test/lib/server/services/eosReport/EosReportService.test.js
- EoS report now have the related runs linked to it
=> [O2B-852] Link runs to EoS automated report

Dockerfile
- Chromium has been updated to 112.0.5615.121-r0 in Dockerfile
=> [O2B-831] Update chromium in dockerfile

lib/public/components/common/selection/dropdown/SelectionDropdownModel.js, lib/public/components/common/toggle/TogglableModel.js, test/public/logs/overview.test.js
- Search inside dropdown selection is now case-insensitive
=> [O2B-854] Make dropdown sort case-insensible

lib/public/views/EosReport/create/ecs/eosFormEcsSpecificPart.js, lib/server/services/eosReport/eosTypeSpecificFormatter/formatEcsEosReportTypeSpecific.js, test/mocks/mock-eos-report.js, test/public/eosReport/creation.test.js
- Run duration is displayed in EoS report
=> [O2B-860] Include run duration in EoS report

lib/domain/dtos/eorReport/CreateEosReportDto.js, lib/public/views/EosReport/create/EosReportCreationModel.js, lib/public/views/EosReport/create/eosReportCreationComponent.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/formatEosReport.js, test/mocks/mock-eos-report.js, test/public/eosReport/creation.test.js
- Shifter name can be modified in EoS report form
=> [O2B-855] Allow sifter name to be modified in EoS report

lib/domain/dtos/eorReport/CreateEosReportDto.js, lib/public/views/EosReport/create/eosReportCreationComponent.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/formatEosReport.js, test/mocks/mock-eos-report.js, test/public/eosReport/creation.test.js
- There is no issues summary block in EoS report anymore
=> [O2B-859] Remove issues summary block from EoS report

.github/workflows/release.yml
- Adds the GH option to allow for manual triggers on release job
=> [OGUI-1350] Add manual trigger of release job

Dockerfile
- Dockerfile git version has been updated
=> [O2B-831] Update git in Dockerfile

lib/server/services/eosReport/getShiftIssues.js, lib/server/services/log/getLogsByTagsInPeriod.js, lib/server/services/shift/getShiftEnvironments.js, test/lib/server/services/eosReport/EosReportService.test.js, test/lib/server/services/log/getLogsByTagsInPeriod.test.js, test/mocks/mock-eos-report.js
- Reply logs do not appear in EoS report
=> [O2B-857] Remove replies from EoS report logs

Dockerfile
- Updated Docker ca-certificates dependency
=> [O2B-831] Update ca-certificates in dockerfile

lib/application.js, lib/config/services.js
- A flag has been added to enable housekeeping, which for now consists in cleaning lost runs & environments
=> [O2B-901] Add flag to enable housekeeping

lib/application.js, lib/database/repositories/EnvironmentHistoryItemRepository.js, lib/server/services/environment/transitionToErrorLostEnvironments.js, lib/server/services/housekeeping/handleLostRunsAndEnvironments.js, lib/server/services/run/setO2StopOfLostRuns.js
- Logs ended and environments transitionned to error by housekeeping script are now logged
=> [O2B-902] Log runs and envs impacted by housekeeping

lib/domain/dtos/eosReport/CreateEosReportDto.js, lib/domain/enums/ShiftTypes.js, lib/public/domain/enums/ShiftTypes.js, lib/public/views/EosReport/create/EosReportCreationModel.js, lib/public/views/EosReport/create/eosReportCreationComponent.js, lib/server/services/eosReport/eosTypeSpecificFormatter/getEosReportTagsByType.js, lib/server/services/eosReport/formatEosReport.js, lib/server/services/shift/ShiftService.js, lib/server/services/shift/getShiftTagsFiltersByType.js, test/api/shift.test.js, test/lib/server/services/eosReport/EosReportService.test.js, test/lib/server/services/eosReport/formatEosReport.test.js, test/lib/server/services/shift/ShiftService.test.js, test/mocks/base-mock-eos-report.js, test/mocks/mock-ecs-eos-report.js, test/mocks/mock-qc-pdp-eos-report.js, test/mocks/mock-slimos-eos-report.js, test/public/eosReport/slimos-creation.test.js, test/public/logs/overview.test.js
- A SLIMOS EoS report has been added
=> [O2B-899] Add slimos EoS report

lib/domain/dtos/eosReport/CreateEosReportDto.js, lib/domain/enums/ShiftTypes.js, lib/public/app.css, lib/public/domain/enums/ShiftTypes.js, lib/public/views/EosReport/create/EosReportCreationModel.js, lib/public/views/EosReport/create/eosReportCreationComponent.js, lib/public/views/EosReport/create/typeSpecific/eosFormQcPdpSpecificPart.js, lib/public/views/EosReport/create/typeSpecific/eosFormShiftLeaderSpecificPart.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/eosTypeSpecificFormatter/formatShiftLeaderEosReportTypeSpecific.js, lib/server/services/eosReport/eosTypeSpecificFormatter/getEosReportTagsByType.js, lib/server/services/eosReport/formatEosReport.js, lib/server/services/eosReport/getShiftIssues.js, lib/server/services/log/getLogsByTagsInPeriod.js, lib/server/services/log/getShiftIssuesTagsOccurrences.js, lib/server/services/shift/ShiftService.js, lib/server/services/shift/formatShiftDate.js, lib/server/services/shift/getShiftTagsFiltersByType.js, test/api/shift.test.js, test/lib/server/services/eosReport/EosReportService.test.js, test/lib/server/services/eosReport/formatEosReport.test.js, test/lib/server/services/shift/ShiftService.test.js, test/mocks/mock-shift-leader-eos-report.js, test/public/eosReport/shift-leader-creation.test.js, test/public/logs/overview.test.js
- The Shift Leader EoS report is now available
=> [O2B-900] Add Shift Leader EoS report

lib/server/controllers/gRPC/GRPCLhcFIllController.js, lib/server/gRPC/servicesImplementationsMappings.js, lib/server/services/lhcFill/LhcFillService.js, lib/server/services/lhcFill/getLastLhcFill.js, lib/server/services/lhcFill/getLhcFill.js, lib/server/services/run/RunService.js, lib/usecases/lhcFill/GetLhcFillUseCase.js, proto/lhcFill.proto, test/lib/server/services/lhcFill/LhcFillService.test.js, test/lib/server/services/lhcFill/index.js, test/lib/usecases/lhcFill/GetLhcFillRunByRunNumberUseCase.test.js
- A new gRPC enpoint has been added to fetch the last LHC fill
=> [O2B-911] Add gRPC endpoint to fetch the last LHC fill

lib/domain/dtos/eosReport/CreateEosReportDto.js, lib/domain/enums/ShiftTypes.js, lib/public/views/EosReport/create/EosReportCreationModel.js, lib/public/views/EosReport/create/eosReportCreationComponent.js, lib/public/views/EosReport/create/typeSpecific/eosFormDcsSpecificPart.js, lib/public/views/EosReport/create/typeSpecific/eosFormShiftLeaderSpecificPart.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/eosTypeSpecificFormatter/formatDcsEosReportTypeSpecific.js, lib/server/services/eosReport/eosTypeSpecificFormatter/formatShiftLeaderEosReportTypeSpecific.js, lib/server/services/eosReport/eosTypeSpecificFormatter/getEosReportTagsByType.js, lib/server/services/eosReport/formatEosReport.js, lib/server/services/shift/getShiftTagsFiltersByType.js, test/lib/server/services/eosReport/EosReportService.test.js, test/lib/server/services/eosReport/formatEosReport.test.js, test/mocks/mock-dcs-eos-report.js, test/public/eosReport/dcs-creation.test.js, test/public/eosReport/index.js
- The DCS EoS report is now available
=> [O2B-915] Add DCS EoS report

test/public/eosReport/shift-leader-creation.test.js
- Fixed EoS report test failing depending on the execution time
=> [O2B-915] Fix time-dependents tests

lib/public/components/NavBar/index.js
- A button to create EoS report has been added
=> [O2B-916] Add a button to create EoS report

lib/public/app.css, lib/public/components/common/contextualMessage/contextualInfo.js, lib/public/views/EosReport/create/eosReportCreationComponent.js
- Hints has been added on some of the EoS reports form fields
=> [O2B-919] Add hints on EoS report

lib/public/app.css, lib/public/components/common/contextualMessage/contextualInfo.js
- Visualy improved the hints icons to be more discrete
=> [O2B-919] Make hints icons more discrete

lib/public/views/Environments/Details/EnvironmentDetailsPage.js, test/public/envs/detailsPage.test.js
- Fix the visibility of environment details badges
=> [O2B-922] Fix environment display badges

lib/domain/entities/Host.js, lib/domain/entities/dpl/DplDetector.js, lib/domain/entities/dpl/DplProcess.js, lib/server/controllers/dplProcess.controller.js, lib/server/services/dpl/DplProcessService.js, lib/server/services/dpl/getDplDetector.js, lib/server/services/dpl/getDplDetectorOrFail.js, lib/server/services/dpl/getDplProcess.js, lib/server/services/dpl/getDplProcessOrFail.js, lib/server/services/host/getHost.js, lib/server/services/host/getHostOrFail.js, test/lib/server/services/dpl/DplProcessService.test.js
- DPL-related services have more options to fetch data
=> [O2B-884] Adapt dpl services to fetch with different properties

cxx-client/CMakeLists.txt, cxx-client/example/exampleProtoServices.cxx, cxx-client/include/BookkeepingApi/BkpClient.h, cxx-client/include/BookkeepingApi/BkpProtoClient.h, cxx-client/include/BookkeepingApi/BkpProtoClientFactory.h, cxx-client/include/BookkeepingApi/DplProcessExecutionProtoClient.h, cxx-client/include/BookkeepingApi/RunProtoClient.h, cxx-client/src/grpc/GrpcBkpProtoClient.cxx, cxx-client/src/grpc/GrpcBkpProtoClient.h, cxx-client/src/grpc/services/GrpcDplProcessExecutionProtoClient.cxx, cxx-client/src/grpc/services/GrpcDplProcessExecutionProtoClient.h, cxx-client/src/grpc/services/GrpcRunProtoClient.h, lib/server/services/dpl/DplProcessService.js, test/api/dplProcess.test.js, test/lib/server/services/dpl/DplProcessService.test.js
- Added DPL process execution endpoint to the gRPC c++ library
=> [O2B-715] Add c++ library for DPL executed processes

lib/public/Model.js, lib/public/views/Runs/Details/RunDetailsModel.js, lib/public/views/Runs/Details/RunDetailsPage.js, lib/public/views/Runs/Details/lhcFillPanel.js, lib/public/views/Runs/Details/runDetailsComponent.js, lib/public/views/Runs/Runs.js, lib/public/views/Tags/Details/TagDetailsModel.js, test/public/flps/detail.test.js, test/public/logs/detail.test.js
- Re-work the run-details page to use the new tabs system
=> [O2B-868] Refactor run details tabs

lib/database/seeders/20230428095106-dpl-executed-processes.js, lib/public/app.css, lib/public/components/common/table/remoteDataTableBody.js, lib/public/components/common/table/table.js, lib/public/components/common/tree/collapsibleTreeNode.js, lib/public/models/CollapsibleTreeNodeModel.js, lib/public/views/Runs/Details/RunDetailsModel.js, lib/public/views/Runs/Details/runDetailsComponent.js
- The list of executed DPL processes are now available in a new tab in run details page
=> [O2B-868] Add DPL process to run details

lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js, lib/public/views/Environments/format/displayEnvironmentStatus.js
- An icon has been added to environment overview to highligh environments that have been to error but are not in error anymore
=> [O2B-924] Add icon to environments error

lib/database/seeders/20230428095027-dpl-detectors.js, lib/database/seeders/20230428095047-dpl-processes.js, lib/database/seeders/20230428095054-hosts.js, lib/database/seeders/20230428095106-dpl-executed-processes.js
- Fixed DPL seeders to await for them to finish
=> [O2B-715] Fix DPL seeders

lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
- Run numbers column is wider on runs overview to improve readability on small screens
=> [O2B-932] Increase runs numbers column width on runs overview page

lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
- LHC period column is wider on runs overview to improve readability on small screens
=> [O2B-932] Increase LHC period column size in runs overview

lib/server/gRPC/services/protoParsing/extractFieldsConverters.js, lib/server/utilities/bigIntConverter.js
- int64 in proto files are casted to javascript numbers, not BigInt (be careful with overflow)
=> [O2B-936] Convert int64 to numbers instead of bigint as temporary workaround for dates

lib/public/Model.js, lib/public/views/About/About.js, lib/public/views/About/Overview/index.js, test/public/about/overview.test.js
- Enhances the about page to include information and status of services including the Bookkeeping gui and the database.
- None
- None
=> O2B-937 About page enhancements

lib/public/Model.js, lib/public/view.js, lib/public/views/LhcFills/Overview/index.js, lib/public/views/Statistics/StatisticsPage.js, lib/public/views/Statistics/StatisticsPageModel.js
- A page to display statistics has been created
=> [O2B-960] Add statistics page

lib/public/app.css, lib/public/components/common/chart/lineChart/lineChartComponent.js, lib/public/components/common/chart/lineChart/renderLineChart.js, lib/public/utilities/createPortal.js, lib/public/views/LhcFills/Overview/index.js, lib/public/views/Statistics/StatisticsPage.js, package-lock.json, package.json
- Line chart display a tooltip with datset's values on point hover
=> [O2B-958] Add tooltip on point hover

lib/database/repositories/Repository.js, lib/server/services/dpl/DplProcessService.js, lib/server/services/dpl/getOrCreateDplDetector.js, lib/server/services/dpl/getOrCreateDplProcess.js, lib/server/services/dpl/getOrCreateDplProcessType.js, lib/server/services/host/getOrCreateHost.js, lib/utilities/cacheAsyncFunction.js, test/lib/utilities/cacheAsyncFunction.test.js, test/lib/utilities/index.js
- DPL processes executions can be inserted concurently in bookkeeping
=> [O2B-933] Allow for concurrent DPL process creation in bookkeeping

lib/database/models/environment.js, lib/server/services/environment/getAllEnvironmentsByLogId.js
=> Fixed incorrectly named environment model

lib/public/views/Runs/ActiveColumns/runsActiveColumns.js, lib/public/views/Runs/Details/runDetailsConfiguration.js
- Show 'Number of EPNs' as 'ON' if nEpns not defined on Run Details page and Run Overview page
=> [O2B-965] Fix for O2B-935 - show EPN as 'ON' if nEpns not defined

lib/public/views/Statistics/StatisticsPage.js
- Efficiency graphs points size have been increased
=> [O2B-972] Increase statistics graphs points size

CHANGELOG.md, lib/server/services/run/createRun.js, test/lib/server/services/run/RunService.test.js
- Run calibrations not being registered has been fixed
=> [O2B-976] Fix calibration runs creation

lib/public/views/Logs/Create/logCreationComponent.js
=> [O2B-991] Remove duplicate LHC fill input in log creation

lib/domain/dtos/UpdateRunDto.js, lib/public/views/Runs/Details/RunPatch.js, lib/public/views/Runs/format/formatRunDetectors.js, lib/server/services/run/RunService.js, lib/usecases/run/UpdateRunUseCase.js, test/api/runs.test.js, test/lib/server/services/run/RunService.test.js, test/lib/usecases/run/UpdateRunUseCase.test.js, test/public/logs/overview.test.js, test/public/runs/detail.test.js
- Detector quality change require justification
=> [O2B-992] Detector quality requires justification

lib/domain/dtos/UpdateRunDto.js, lib/public/views/Runs/Details/RunPatch.js, lib/public/views/Runs/format/formatRunQuality.js, lib/server/services/run/RunService.js, lib/server/services/run/logEntriesCreation/logRunQualityChange.js, lib/server/services/run/updateRun.js, lib/usecases/run/UpdateRunUseCase.js, test/api/runs.test.js, test/lib/server/services/run/RunService.test.js, test/lib/usecases/run/UpdateRunUseCase.test.js, test/public/logs/overview.test.js
- Updating run quality require justification
=> [O2B-993] Run quality update require justification

lib/public/Model.js, lib/public/components/common/errorAlert.js, lib/public/views/LhcFills/Detail/lhcFillDetailsComponent.js, lib/public/views/Logs/Create/LogCreationModel.js, lib/public/views/Logs/Create/LogCreationPage.js, lib/public/views/Logs/Logs.js, lib/public/views/Runs/Details/runDetailsComponent.js, test/public/lhcFills/detail.test.js, test/public/runs/detail.test.js
- A button to create a log is now availlable in LHC fill details page
=> [O2B-999] Add a button to create log from LHC fill details page

lib/public/views/EosReport/create/typeSpecific/commentInput.js, lib/public/views/EosReport/create/typeSpecific/eosFormEcsSpecificPart.js, lib/public/views/Runs/format/formatRunCalibrationStatus.js, lib/public/views/Runs/format/formatRunDetectors.js, lib/public/views/Runs/format/formatRunQuality.js
- Run edition justification inputs are now visually similar to other inputs
=> [O2B-1003] Make justification input like other inputs

lib/public/views/Environments/Details/EnvironmentDetailsPage.js, lib/public/views/Logs/Create/LogCreationModel.js, lib/public/views/Logs/Logs.js, test/public/envs/detailsPage.test.js
- A button has been added to create log for a given environment
=> [O2B-998] Add a button to create log from environment details page

CHANGELOG.md, package-lock.json, package.json
=> Release 0.65.0

docs/backend-architecture.md, lib/domain/dtos/DtoFactory.js, lib/server/controllers/lhcFill.controller.js, lib/server/routers/lhcFills.router.js, lib/server/services/log/LogService.js, lib/usecases/log/GetAllLogsUseCase.js, test/api/lhcFills.test.js, test/lib/server/services/log/LogService.test.js
- An endpoint has been added to fetch all the logs for a given LHC fill
=> [O2B-1001] Add endpoint to fetch logs of a given LHC fill

lib/public/components/common/chart/lineChart/renderLineChart.js
- Fixed the alignment of chart tooltip
=> [O2B-1011] Fix chart tooltip alignment

lib/server/controllers/environments.controller.js, lib/server/routers/environments.router.js, lib/server/services/log/LogService.js, test/api/environments.test.js, test/lib/server/services/log/LogService.test.js
- Added endpoint to fetch all the logs for a given environment
=> [O2B-1002] Add endpoint to fetch environments logs

lib/public/components/common/selection/SelectionModel.js, lib/public/components/common/selection/dropdown/SelectionDropdownModel.js, lib/public/components/tag/tagToOption.js, lib/public/components/tag/tagToOptionWithArchiveBadge.js, lib/public/utilities/createPortal.js, test/public/logs/overview.test.js
- An icon with tooltip has been added to tag pickers to display description
=> [O2B-849] Add tag description

lib/public/views/Environments/Details/EnvironmentDetailsPage.js, test/public/envs/detailsPage.test.js
- Removed the title from environments run tab
=> [O2B-1002] Remove run tab title

lib/public/app.css, lib/public/components/common/chart/lineChart/lineChartComponent.js, lib/public/components/common/chart/lineChart/renderLineChart.js, lib/public/components/common/chart/rendering/axis/AxisRenderer.js, lib/public/components/common/chart/rendering/grid/renderHorizontalGrid.js
- Horizontal lines are displayed in front of axis ticks
=> [O2B-1015] Display horizontal line for ticks

lib/public/components/common/chart/lineChart/renderLineChart.js, lib/public/components/common/chart/rendering/dataset/renderDatasetAsLine.js, lib/public/views/Statistics/StatisticsPage.js, lib/public/views/Statistics/StatisticsPageModel.js, lib/public/views/Statistics/charts/meanRunDurationChartComponent.js
- Added mean run duration graph
=> [O2B-1016] Add mean duration graph

docker-compose.yml
- Aligned mariadb docker version on production version
=> [O2B-831] Use mariadb production version in docker

lib/public/app.css, lib/public/components/common/popover/overflowBalloon.js, lib/public/components/common/popover/tooltip.js, test/public/defaults.js, test/public/logs/overview.test.js, test/public/runs/overview.test.js
- Fixed popover misbehaving when cursor moves from child element to parent element
=> [O2B-1017] Fix popover misbehavior when moving from parent to child elt

lib/public/views/Runs/ActiveColumns/runsActiveColumns.js, lib/server/services/environment/EnvironmentService.js, lib/server/services/lhcFill/LhcFillService.js
- End of runs reasons are displayed in environments and LHC fills details pages
=> [O2B-913] Display EoR in env and LHC fill details

lib/database/repositories/StableBeamRunsRepository.js, test/lib/server/services/statistics/StatisticsService.test.js
- Fixed the misbehaving time between runs graphs
=> [O2B-1018] Fixed "over 30min" time between runs bin

test/public/flps/overview.test.js, test/public/logs/overview.test.js, test/public/runs/overview.test.js
- Fixed infinite selector failing tests
=> [O2B-1023] Fix infinite amount selector tests

lib/public/components/common/selection/dropdown/selectionDropdown.js
- Fixed the popover of tag description not being displayed after filtering
=> [O2B-1031] Fix tag popover

package.json
- NA
- use newer `docker compose` syntax instead of legacy `docker-compose`
- NA
=> use newer docker command syntax

lib/public/app.css, lib/public/components/Filters/common/filtersPanel.js, lib/public/components/Filters/common/filtersToggleButton.js, lib/public/components/Pagination/amountSelector.js, lib/public/components/common/popover/PopoverEngine.js, lib/public/components/common/popover/dropdown.js, lib/public/components/common/popover/overflowBalloon.js, lib/public/components/common/popover/popover.js, lib/public/components/common/popover/tooltip.js, lib/public/components/common/selection/dropdown/SelectionDropdownModel.js, lib/public/components/common/selection/dropdown/selectionDropdown.js, lib/public/components/common/toggle/toggleContainer.js, lib/public/components/modal/modalContainer.js, lib/public/utilities/createPortal.js, lib/public/utilities/documentClickTaggedEventRegistry.js, lib/public/view.js, lib/public/views/Logs/Logs.js, lib/public/views/Runs/Runs.js, lib/public/views/Runs/format/formatRunDetectors.js, test/public/defaults.js, test/public/logs/overview.test.js, test/public/runs/detail.test.js, test/public/runs/overview.test.js
- Popover can now be openend in any direction relatively to the trigger
=> [O2B-913] Make popover system generic

lib/application.js, lib/config/index.js, lib/config/services.js, lib/presentation/Component.js, lib/public/app.css, lib/public/index.html, lib/public/services/externalRouting/getInfologgerLink.js, lib/public/views/Environments/ActiveColumns/environmentsActiveColumns.js, lib/public/views/Environments/Details/EnvironmentDetailsPage.js, lib/public/views/Environments/format/displayEnvironmentInfologgerLinks.js, lib/public/views/Runs/ActiveColumns/runsActiveColumns.js, lib/public/views/Runs/Details/runDetailsComponent.js, lib/public/views/Runs/format/displayRunNumber.js, lib/server/controllers/configuration.controller.js, lib/server/controllers/index.js, lib/server/routers/configuration.router.js, lib/server/routers/index.js, lib/server/services/housekeeping/handleLostRunsAndEnvironments.js, test/api/configuration.test.js, test/api/index.js
- Infologger links has been added in run overview, run details, environment overview and environment details
=> [O2B-913] Add infologger links

CHANGELOG.md, package-lock.json, package.json
=> Release 0.69.0

lib/public/services/externalRouting/getInfologgerLink.js
=> [O2B-1034] Fix infologger run link

lib/database/repositories/StableBeamRunsRepository.js, lib/database/seeders/20221006084006-run-detectors.js, lib/server/controllers/gRPC/GRPCDplProcessExecutionController.js, lib/server/controllers/statistics.controller.js, lib/server/routers/statistics.router.js, lib/server/services/statistics/StatisticsService.js, test/lib/server/services/statistics/StatisticsService.test.js
- Added endpoint to fetch detectors efficiency
=> [O2B-1033] Add endpoint to fetch detector efficiency

lib/public/services/lhcFill/LhcFillStatisticsExtractor.js, lib/public/utilities/formatting/formatPercentage.js, lib/public/views/Statistics/charts/efficiencyChartComponent.js
- Improved `formatPercentage` to use normalized values ([0, 1])
=> [O2B-1033] Improve percentage format

lib/public/components/common/chart/rendering/ChartRenderer.js, lib/public/components/common/chart/rendering/HistogramChartRenderer.js, lib/public/components/common/chart/rendering/PointBasedChartRenderer.js, lib/public/components/common/chart/rendering/axis/AxisRenderer.js, lib/public/components/common/chart/rendering/dataset/renderDatasetAsLine.js, lib/public/components/common/chart/rendering/dataset/renderDatasetAsPointCloud.js, lib/public/views/Statistics/charts/efficiencyChartComponent.js
- Efficiency graph vertical axis is forced between 0 and 100%
- Chart axis limits can be overiden
=> [O2B-1033] Add possibility to override min/max in graphs

lib/public/components/common/chart/lineChart/lineChartComponent.js, lib/public/components/common/chart/rendering/PointBasedChartRenderer.js
- Fixed bugs in chart renderer:
- Fixed popover staying displayed when cursor moves out of the graph
- Fixed graph not updating in some specific conditions
=> [O2B-1033] Add several improvements to the chart rendering system

lib/server/controllers/runs.controller.js, lib/server/routers/runs.router.js
- NA
- remove dead code (/api/runs/endpoint)
- NA
=> [O2B-1036] remove /runs/tags/ endpoint

lib/domain/dtos/filters/RunFilterDto.js, lib/usecases/run/GetAllRunsUseCase.js, test/api/runs.test.js, test/lib/usecases/run/GetAllRunsUseCase.test.js
- Run API allow filtering on calibration status
=> [O2B-1037] Allow filtering on calibration status in runs API

lib/public/app.css, lib/public/components/common/form/switchInput.js, lib/public/utilities/fetch/RemoteDataFetcher.js, lib/public/utilities/fetch/buildUrl.js, lib/public/views/Statistics/StatisticsPage.js, lib/public/views/Statistics/StatisticsPageModel.js, lib/public/views/Statistics/chartColors.js, lib/public/views/Statistics/charts/detectorsEfficienciesComponent.js
- Detectors efficiencies graphs has been added
=> [O2B-1033] Add detector efficiency graphs

lib/database/repositories/LogRepository.js, lib/public/components/common/chart/rendering/axis/AxisRenderer.js, lib/public/views/Statistics/StatisticsPage.js, lib/public/views/Statistics/StatisticsPageModel.js, lib/public/views/Statistics/charts/tagOccurrencesBarChartComponent.js, lib/server/controllers/statistics.controller.js, lib/server/routers/statistics.router.js, lib/server/services/statistics/StatisticsService.js, test/lib/server/services/statistics/StatisticsService.test.js, test/lib/server/services/statistics/index.js
- Added tag occurences in logs
=> [O2B-1035] Add tag occurrences in logs chart

lib/database/index.js, lib/database/repositories/EorReasonRepository.js, lib/database/utilities/QueryBuilder.js, lib/public/Model.js, lib/public/components/Detail/detailsGrid.js, lib/public/components/Detail/detailsList.js, lib/public/components/Filters/RunsFilter/dcs.js, lib/public/components/Filters/RunsFilter/ddflp.js, lib/public/components/Filters/RunsFilter/epn.js, lib/public/components/Filters/common/filters/checkboxFilter.js, lib/public/components/Log/logText.js, lib/public/components/NavBar/index.js, lib/public/components/Pagination/pageSelector.js, lib/public/components/common/table/rows.js, lib/public/utilities/export.js, lib/public/utilities/scrollTo.js, lib/public/utilities/targetURL.js, lib/public/views/Environments/ColoredEnvironmentStatusComponent.js, lib/public/views/Flps/Flps.js, lib/public/views/Logs/ActiveColumns/logsActiveColumns.js, lib/public/views/Logs/Logs.js, lib/public/views/Runs/Runs.js, lib/public/views/Tags/Create/TagCreationModel.js, lib/server/routers/index.js, lib/server/services/eosReport/formatEosReport.js, lib/server/services/log/getLogsByTitle.js, lib/server/services/shift/ShiftService.js, lib/utilities/env-utils.js, lib/utilities/isPromise.js, test/public/defaults.js
- NA
- refactor docs: scalar types to lowercase
- NA
=> scalars to lowercase

lib/public/components/common/chart/rendering/dataset/renderDatasetAsLine.js
- Fixed misbehaving in chart fill conditions
=> [O2B-1047] Fixed line chart fill

lib/public/app.css, lib/public/components/Filters/common/FilterModel.js, lib/public/components/Filters/common/filters/TimeRangeFilterModel.js, lib/public/components/Filters/common/filters/timeRangeFilter.js, lib/public/components/common/form/inputs/DateTimeInputModel.js, lib/public/components/common/form/inputs/dateTimeInput.js, lib/public/utilities/dateUtils.js, lib/public/utilities/formatting/HTMLInputDateFormat.js, lib/public/views/EosReport/create/typeSpecific/commentInput.js, lib/public/views/EosReport/create/typeSpecific/eosFormEcsSpecificPart.js, lib/public/views/Runs/format/editRunEorReasons.js, lib/public/views/Statistics/StatisticsPage.js, lib/public/views/Statistics/StatisticsPageModel.js
- User can now chose the date range on which statistics must be applied
- A time range picker has been created
=> [O2B-1043] Add time filter

lib/database/repositories/StableBeamRunsRepository.js, lib/public/components/Filters/common/filters/TimeRangeFilterModel.js, lib/public/views/Runs/ActiveColumns/runsActiveColumns.js, lib/public/views/Runs/format/displayRunEorReasonOverview.js, lib/public/views/Runs/format/displayRunEorReasons.js, lib/public/views/Runs/format/formatEorReason.js, lib/public/views/Statistics/StatisticsPage.js, lib/public/views/Statistics/StatisticsPageModel.js, lib/public/views/Statistics/charts/eorReasonOccurrencesBarChartComponent.js, lib/server/controllers/statistics.controller.js, lib/server/routers/statistics.router.js, lib/server/services/statistics/StatisticsService.js, test/lib/server/services/statistics/StatisticsService.test.js
=> [O2B-1050] Added EoR reason chart

lib/database/repositories/StableBeamRunsRepository.js, lib/database/seeders/20220513153907-eor-reason.js, test/lib/usecases/run/UpdateRunUseCase.test.js, test/public/runs/overview.test.js
- EoR reasons are grouped by category, title in EoR reasons chart
=> [O2B-1050] Group EoR reasons by category,title in EoR reasons chart

lib/public/app.css, lib/public/components/Filters/common/filters/TimeRangeFilterModel.js, lib/public/components/Filters/common/filters/timeRangeFilter.js, lib/public/components/common/formatting/formatTimeRange.js, lib/public/utilities/dateUtils.js, lib/public/views/LhcFills/Overview/index.js, lib/public/views/Statistics/StatisticsPage.js, lib/public/views/Statistics/StatisticsPageModel.js
- Added pre-fill options to the time filter
=> [O2B-1043] Add pre-filled options for time range filter

lib/database/migrations/20231025101611-create-lhc-periods-view.js, lib/server/services/lhcPeriod/LhcPeriodStatisticsService.js
- NA
- NA
- alter lhc periods view and related subquery to work upon good runs only
=> [O2B-1024] get only good runs

Dockerfile
- [NA] tests are added
- [NA] documentation was updated or added
-
- update chromium dependencies to fix pipeline
-
=> [fix] Update Dockerfile

lib/public/components/common/chart/lineChart/lineChartComponent.js
- Remove spurious rendering on chart hover
=> [O2B-1074] Remove spurious re-render on chart hover

lib/public/components/common/form/inputs/DateTimeInputModel.js, lib/public/components/common/formatting/formatTimeRange.js, lib/public/views/Statistics/StatisticsPageModel.js
- Fixed time input clear re-render
=> [O2B-1075] Fix time input filter clear re-render

lib/public/Model.js, lib/public/views/Home/Overview/index.js, lib/public/views/Logs/Create/LogCreationModel.js, lib/public/views/Logs/LogsModel.js, lib/public/views/Logs/Overview/LogsOverviewModel.js, lib/public/views/Logs/Overview/index.js, test/public/logs/overview.test.js
- NA
- refactor LogsModel, extract overview to separate class
- NA
=> [O2B-1081] logs refactor

lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewPage.js
- style LHC Periods page filter button the same way as other pages
- NA
- NA
=> Add padding for filter button in LHC Periods page

lib/public/components/common/popover/PopoverEngine.js, lib/public/components/common/popover/popover.js
- A margin has been added between the popover and the screen edges
=> [O2B-1077] Add margins between popover and screen edges

lib/public/views/Logs/Overview/LogsOverviewModel.js
- Error does not show up when going back to no value
- none
- none
=> [O2B-1066]: Added extra check for empty for log environment filter

lib/database/migrations/20231211080706-create-data-passes.js, lib/database/models/dataPass.js, lib/database/models/index.js, lib/database/models/typedefs/SequelizeDataPass.js
- NA
- NA
- add migration file for data passes table creation
=> [O2B-1092] add migration file

lib/public/views/Logs/Details/logTreeViewComponent.js
- Fixed links of attachment in log tree
=> [O2B-1095] Fix log's attachment token

lib/database/migrations/20240108090706-create-data-passes-runs.js, lib/database/models/dataPass.js, lib/database/models/run.js
- NA
- NA
- adds association between data passes and runs
=> [O2B-1092] add migration data passes runs migration

lib/database/migrations/20231211080706-create-data-passes.js, lib/database/migrations/20240109091430-add-unique-constraint-to-data-passes.js
- NA
- NA
- add unique constraint to column `name` of data_passes table
=> Add unique constraint to column name of data_passes column

lib/application.js, lib/server/services/ScheduledProcessesManager.js, test/lib/server/services/ScheduledProcessesManager.test.js
- Added a service to schedule processes and applied it to the existing handling of lost envs and runs
=> [O2B-1112] Add scheduled process manager

lib/server/monalisa-synchronization/MonALISASynchronizer.js
- NA
- add necessary argument to logger method
- NA
=> [O2B-1093] Add argument to logging method

lib/public/models/OverviewModel.js
- NA
- Revoke changes dependent on https://github.com/AliceO2Group/WebUi/pull/2219
- NA
=> [O2B-1087] Remove clause 'other'

lib/public/components/common/chart/lineChart/lineChartComponent.js
=> Remove chart dead code

lib/database/migrations/20240119152741-add-history-items-fk.js
- Added missing key to the environments history items table
=> [O2B-532] Add missing foreign key to history items

lib/public/views/Runs/Details/runDetailsComponent.js, lib/server/services/dpl/DplProcessService.js
The DPL tasks tree will now display "NO DETECTOR" when no detector has been found.
Task type information is now displayed after the process type name in the DPL tasks tree.
=> [O2B-987] Improvements of DPL processes tree

lib/server/services/dpl/DplProcessService.js, test/api/dplProcess.test.js, test/lib/server/services/dpl/DplProcessService.test.js
Ensure alphabetical sorting for DPL tasks.
=> [O2B-988] Sort DPL tasks alphabetically

lib/database/migrations/20240124112734-add-runs-env-id-index.js, lib/usecases/environment/GetAllEnvironmentsUseCase.js
- Fixed the environments overview page crash
=> [O2B-1110] Fetch runs in sub-query in environments

lib/public/views/lhcPeriods/ActiveColumns/lhcPeriodsActiveColumns.js, lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewPage.js, test/public/lhcPeriods/overview.test.js
- Unify 'Runs' button stying in LHC Periods view to other BKP components
- Use badge for runsCount
- Increase number of default rows in LHC Periods view
- NA
- NA
=> [O2B-1136] Unify LHC Periods view styling

lib/public/app.css, lib/public/components/common/popover/overflowBalloon.js, lib/public/views/Runs/format/formatRunDetectorsInline.js
- Fixed popover balloon being displayed on every detectors list in runs
- Fixed the border for detector quality being cropped by overflow hidden
=> [O2B-883] Fix runs quality border triggering balloon display

lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewPage.js
- Change title style in Runs Per LHC Period view
- NA
- NA
=> [O2B-1141] Unify style of Runs Per LHC Period view title

lib/database/seeders/20200426144121-users.js
- none
- Seeding does not throw validation error if you already visited the application before seeding.
- none
=> [02B-1146] Fixed users seeders to use auto generated pk to avoid conflicts

package.json
- All dependencies has been added to the bundle dependencies
=> Add all dependencies to bundled dependencies

lib/server/services/dataPasses/DataPassService.js, test/lib/server/services/dataPasses/DataPassesService.test.js
=> Fix typos in Dass Pass Service

lib/public/Model.js, lib/public/components/Filters/common/filters/TextTokensFilterModel.js, lib/public/components/Log/logReplyButton.js, lib/public/components/common/panel/LabelPanelHeaderComponent.js, lib/public/components/common/panel/PanelComponent.js, lib/public/view.js, lib/public/views/Logs/Create/LogCreationModel.js, lib/public/views/Logs/Create/LogReplyModel.js, lib/public/views/Logs/Create/LogReplyPage.js, lib/public/views/Logs/Create/logCreationComponent.js, lib/public/views/Logs/Create/logReplyComponent.js, lib/public/views/Logs/Create/panels/LogCreationContentPanel.js, lib/public/views/Logs/LogsModel.js, test/public/logs/create.test.js, test/public/logs/detail.test.js, test/public/runs/detail.test.js
- Log reply has its dedicated page
=> [O2B-1106] Separate log reply from log creation

lib/public/components/common/errorAlert.js, lib/public/views/Runs/Details/RunDetailsModel.js, lib/public/views/Runs/Details/RunPatch.js, lib/public/views/Runs/Details/runDetailsComponent.js
- Fixed run quality being sent in patch even if it has not been updated
- Display errors when update run fails
=> [O2B-1165] Do not send run quality in run update patch when it do not applies

test/public/defaults.js, test/public/flps/detail.test.js, test/public/logs/create.test.js, test/public/logs/detail.test.js, test/public/runs/runsPerDataPass.overview.test.js, test/public/runs/runsPerPeriod.overview.test.js
- Removed wait for timeout longer than 1s from tests
=> Try to remove `waitForTimeout` lasting more than a second

lib/server/services/shift/getShiftTagsFiltersByType.js, test/api/shift.test.js, test/api/tags.test.js, test/lib/server/services/shift/ShiftService.test.js, test/lib/usecases/log/GetAllLogsUseCase.test.js, test/mocks/mock-shift-leader-eos-report.js
- SL EoS report now include the three shifter's logs
=> [O2B-1167] Include shifters logs in SL EoS report

lib/server/controllers/logs.controller.js, lib/server/routers/logs.router.js, lib/server/services/log/LogService.js, test/api/logs.test.js, test/lib/server/services/log/LogService.test.js
- none
- New endpoint added that uses a log id to fetch it's child logs
=> [O2B-905] Add endpoint to fetch all replies to a given log using its id

lib/public/views/Statistics/StatisticsPageModel.js
- Fixed detectors efficiency statistics tab
=> [O2B-1169] Fix detectors efficiency statistics tab

lib/domain/dtos/eosReport/CreateEosReportDto.js, lib/public/components/common/form/inputs/DateTimeInputComponent.js, lib/public/components/common/form/inputs/DateTimeInputModel.js, lib/public/components/common/form/inputs/TimestampInputComponent.js, lib/public/components/common/form/magnetsConfiguration/AliceMagnetsConfigurationSnapshotsForm.js, lib/public/components/common/form/magnetsConfiguration/aliceMagnetsConfigurationsSnapshotsForm.js, lib/public/utilities/formatting/dateTimeInputFormatters.mjs, lib/public/views/EosReport/create/EosReportCreationModel.js, lib/public/views/EosReport/create/typeSpecific/eosFormShiftLeaderSpecificPart.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/eosTypeSpecificFormatter/formatShiftLeaderEosReportTypeSpecific.js, test/mocks/mock-shift-leader-eos-report.js, test/public/eosReport/shift-leader-creation.test.js
- Magnets input in SL EoS report now require date
- Extracted a magnet filling input
=> [O2B-1140] Extract ALICE magnets configuration snapshot form component

lib/public/components/common/form/inputs/DateTimeInputComponent.js, lib/public/components/common/form/inputs/DateTimeInputModel.js, lib/public/utilities/formatting/dateTimeInputFormatters.mjs, test/public/eosReport/shift-leader-creation.test.js
- Fixed statistics input displaying error with valid values
- Fixed setting value of date time input with minutes granularity
=> [O2B-1140] Fix time range input when granularity is minutes

lib/public/views/Runs/Overview/RunsOverviewModel.js, test/public/runs/runsPerPeriod.overview.test.js, test/utilities/waitForDownload.js
- Fixed bug concerning runs export of Run Per LHC Period page, not only good, physics were included
- NA
- NA
=> [O2B-1193] - Runs Per LHC Period export bugfix

test/utilities/waitForDownload.js
- NA
- Fixed message format in tests
- NA
=> Fix message format in tests

lib/public/components/detector/DetectorSelectionDropdownModel.js, lib/public/services/detectors/detectorsProvider.js, lib/public/utilities/ObservableData.js, lib/public/views/Logs/Create/OnCallLogTemplate.js, lib/public/views/Runs/Details/RunDetailsModel.js, lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js, lib/public/views/Runs/RunPerPeriod/RunsPerLhcPeriodOverviewModel.js
- Use observable data for detectors provider
=> [O2B-1140] Use observable data for detector provider

lib/public/views/DataPasses/ActiveColumns/dataPassesActiveColumns.js, test/public/dataPasses/overviewPerLhcPeriod.test.js
- Added formatting to following columns in Data Passes view:
- Output Size 
- Reconstructed Events
- NA
- NA
=> [O2B-1196] Add formatting to Data Passes view

Dockerfile
- NA
- Updated CA certificates alpine package
- NA
=> Update docker dependencies

lib/database/seeders/20240213120811-quality-control-flags.js, lib/server/controllers/qcFlagTypes.controller.js, lib/server/routers/qcFlagTypes.router.js, lib/server/services/qualityControlFlag/QcFlagTypeService.js, test/api/qcFlagTypes.test.js, test/lib/server/services/qualityControlFlag/QcFlagTypeService.test.js
- NA
- Added fetch all QC flag types endpoint
- NA
=> [O2B-1183] Add QC flag types fetch all endpoint

lib/database/seeders/20200508094502-logs.js, lib/public/components/common/table/rows.js, lib/public/views/Logs/Overview/index.js, test/lib/server/services/log/getLogsByUserInPeriod.test.js, test/public/dataPasses/overviewPerLhcPeriod.test.js, test/public/defaults.js, test/public/lhcPeriods/overview.test.js, test/public/logs/overview.test.js, test/public/simulationPasses/overviewAnchoredSimulationPasses.test.js, test/public/simulationPasses/overviewPerLhcPeriod.test.js
- Added tests for no-anonymous toggle in logs overview
- Added column-specific class to every table cells to be used in tests to fetch the content of all the cells of one column
=> [O2B-1181] Add tests for no-anonymous logs toggle

lib/domain/dtos/GetAllLogsDto.js, lib/domain/entities/LhcFill.js, lib/public/app.css, lib/public/components/common/badge.js, lib/public/components/common/chart/rendering/BarChartRenderer.js, lib/public/components/common/panel/PanelComponent.js, lib/public/components/common/table/rows.js, lib/public/utilities/formatting/formatFullDate.js, lib/public/utilities/formatting/formatTimeAndEfficiencyLoss.js, lib/public/views/Logs/Create/TemplatedLogCreationModel.js, lib/public/views/Logs/Create/logCreationComponent.js, lib/public/views/Logs/Create/templates/OnCallLogTemplate.js, lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js, lib/public/views/Logs/Create/templates/onCallLogCreationConfiguration.js, lib/public/views/Logs/Create/templates/rcDailyMeetingConfiguration.js, lib/public/views/Runs/ActiveColumns/runsActiveColumns.js, lib/server/services/log/LogService.js, lib/server/services/log/getLogsByTagsInPeriod.js, lib/usecases/log/GetAllLogsUseCase.js, test/lib/server/utilities/bigIntConverter.test.js, test/utilities/waitForDownload.js
- Added log creation template for RC daily meeting
=> [O2B-1140] Create RC daily meeting template

lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewModel.js, test/public/defaults.js, test/public/lhcPeriods/overview.test.js
- Fixed resetting of beamType filter
- Extended and refactored LHC Period overview tests
- NA
=> [O2B-1197] Fix resetting of beamType filter

lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
- NA
- Added merging similar errors for MonALISA Synchroniser to prevent logs overflow
- NA
=> Reduced MonALISA Synchroniser error logs

.github/workflows/bookkeeping.yml, .github/workflows/docker.yml, docs/DOCKER.md, docs/get-started.md
- Replaced `docker-compose` by `docker compose` everywhere
=> [O2B-1207] Replace docker-compose by docker compose

lib/public/models/OverviewModel.js, lib/public/views/DataPasses/PerLhcPeriodOverview/DataPassesPerLhcPeriodOverviewModel.js, lib/public/views/DataPasses/PerLhcPeriodOverview/DataPassesPerLhcPeriodOverviewView.js, lib/public/views/QcFlagTypes/Overview/QcFlagTypesOverviewModel.js, lib/public/views/SimulationPasses/AnchoredOverview/AnchoredSimulationPassesOverviewModel.js, lib/public/views/SimulationPasses/PerLhcPeriodOverview/SimulationPassesPerLhcPeriodOverviewModel.js, lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewModel.js, lib/public/views/lhcPeriods/Overview/LhcPeriodsOverviewPage.js
- NA
-  Moved sort model declaration to generic overview model
- NA
=> [O2B-1138] Move sort model declaration to generic overview model

test/api/index.js
- NA
- Removed redundant test suite call
- NA
=> Remove redundant test suite call

lib/public/app.css, lib/public/views/Logs/Create/logCreationComponent.js
- Fixed log reply displaying oversized left panel
=> [O2B-1209] Fix log reply main panel size

lib/server/routers/index.js
- Fixed error at startup stating that routes have no property args
=> [O2B-821] Add default routes args

lib/public/components/common/panel/PanelComponent.js
- Fixed log creation inputs having incoherent heights
=> [O2B-1209] Fix panel sizing in logs

lib/public/views/Runs/Details/runDetailsComponent.js
- Fixed LHC fill number not being filled when creating a log from run details page
=> Fix fill number not being filled when creating log for run

lib/public/components/Filters/common/filters/timeRangeFilter.js, lib/public/components/common/form/inputs/TimeRangeInputComponent.js, lib/public/views/QcFlags/Create/ForDataPass/QcFlagCreationForDataPassPage.js, lib/public/views/QcFlags/Create/qcFlagCreationComponent.js
- Minor visual improvements of QC falg creation page
=> [O2B-1155] Visual improvements of QC flag creation

lib/domain/dtos/filters/RunFilterDto.js, lib/public/components/Filters/RunsFilter/DetectorsFilterModel.js, lib/public/components/Filters/common/CombinationOperatorChoiceModel.js, lib/public/components/Filters/common/TagFilterModel.js, lib/public/views/Runs/Overview/RunsOverviewModel.js, lib/usecases/run/GetAllRunsUseCase.js, test/api/runs.test.js, test/lib/usecases/run/GetAllRunsUseCase.test.js, test/public/runs/overview.test.js
- Added possibility to filter out runs that contains any of the given tags
=> [O2B-1214] Allow filtering runs on none of the tags

test/public/defaults.js
=> Fix randomly failing QC flag type test

proto/common.proto
- Run optional properties are now optional in proto file
=> [O2B-894] Mark run nullable properties as optional in proto

lib/public/views/QcFlags/details/forDataPass/QcFlagDetailsForDataPassPage.js, lib/public/views/QcFlags/details/forSimulationPass/QcFlagDetailsForSimulationPassPage.js, lib/server/controllers/qcFlag.controller.js, lib/server/routers/qcFlag.router.js, lib/server/services/qualityControlFlag/QcFlagService.js, test/api/qcFlags.test.js, test/lib/server/services/qualityControlFlag/QcFlagService.test.js
- Changed QC flag delete button accessibility to admins only
- NA
- NA
=> [O2B-1216] Change QC flag delete button accessibility to admins only

lib/database/adapters/LhcFillStatisticsAdapter.js, lib/database/migrations/20240423072839-add-sb-duration-to-fill-statistics-view.js, lib/database/models/lhcFillStatistics.js, lib/database/models/typedefs/SequelizeLhcFillStatistics.js, lib/domain/entities/statistics/LhcFillStatistics.js, lib/public/services/lhcFill/LhcFillStatisticsExtractor.js, lib/public/views/Statistics/charts/efficiencyChartComponent.js
- ALICE efficiency computation now uses mean weigthed by stable beam duration
=> [O2B-1224] Use weighted means for ALICE efficiency in statistics

lib/database/repositories/Repository.js, lib/server/services/log/LogService.js, lib/usecases/log/GetAllLogsUseCase.js, test/public/lhcFills/detail.test.js
- Log overview loading time has been improved:
- Before: ~5.5s to load 10 logs out of ~85000
- After: ~60ms to load 10 logs out of ~85000
- Author and tags are now included in the LHC fill details page
=> [O2B-1232] Add author and tags to get all logs

test/public/logs/create.test.js
- Fixed randomly failing test on RC daily minutes template
=> [O2B-1227] Fix randomly failing tests induced for RC template

test/public/logs/create.test.js
- Fixed RC template tests failling in the morning
=> [O2B-1227] Fix RC template tests failing in the morning

lib/server/controllers/qcFlag.controller.js, lib/server/services/dpl/getPhysicalDplDetectorOrFail.js, lib/server/services/qualityControlFlag/QcFlagService.js, test/lib/server/services/qualityControlFlag/QcFlagService.test.js
- Cleaned the QC flag craetion service to be used for gRPC interface
=> [O2B-1153] Preliminary QC flag service refactoring

lib/public/domain/enums/detectorsNames.js, lib/public/services/detectors/detectorsNames.js, lib/public/services/detectors/detectorsProvider.js, lib/public/services/detectors/dplDetectorsProvider.js
- Set DPL detectors order in RCT views 
- NA
- NA
=> [O2B-1253] Set DPL detectors order in RCT views

lib/public/services/detectors/dplDetectorsProvider.js
- Fixed detectors order
- NA
- NA
=> [O2B-1260] Fix detectors order

test/public/qcFlags/forDataPassCreation.test.js, test/public/qcFlags/forSimulationPassCreation.test.js
- NA
- Changed why of checking values in table in QC flags tests
- NA
=> Fix QC flags tests

lib/public/components/qcFlags/qcSummaryColors.js, lib/public/components/qcFlags/qcSummaryLegendTooltip.js, lib/public/components/qcFlags/qcSummaryTooltip.js, lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js, lib/public/views/Runs/Overview/exportRunsTriggerAndModal.js, lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js, lib/public/views/Runs/RunsPerSimulationPass/RunsPerSimulationPassOverviewPage.js
- Added QC summary legend to Runs Per Data/Simulation Pass overviews
- NA
- NA
=> [O2B-1259] Add QC flags legend

lib/server/controllers/gRPC/GRPCEnvironmentController.js, lib/server/controllers/gRPC/GRPCRunController.js, lib/server/gRPC/bindGRPCController.js, lib/server/gRPC/services/protoParsing/extractFieldsConverters.js, proto/environment.proto, test/gRPC/extractFieldConverters.test.js, test/gRPC/proto/main.proto, test/gRPC/serviceImplementation.test.js
- Repeated fields in proto files are now properly handled
=> [O2B-1153] Handle repeated fields in proto files

lib/server/controllers/gRPC/GRPCEnvironmentController.js, lib/server/controllers/gRPC/GRPCQcFlagController.js, proto/qcFlag.proto
- Handle properly the nullable numbers from protobuf, not mistakenly converting them to NaN
- Made QC flag creation from and to nullable in protobuf file
=> [O2B-1270] Handle properly nullable numbers from protobuf

.github/workflows/bookkeeping.yml
=> [O2B-1279] time-out increased to 20 minutes

lib/public/components/common/form/inputs/TimestampInputComponent.js, lib/public/components/common/form/magnetsConfiguration/AliceMagnetsConfigurationSnapshotsForm.js, lib/public/components/common/form/magnetsConfiguration/aliceMagnetsConfigurationsSnapshotsForm.js, lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js, lib/server/services/eosReport/EosReportService.js, lib/server/services/eosReport/eosTypeSpecificFormatter/formatShiftLeaderEosReportTypeSpecific.js, test/mocks/mock-shift-leader-eos-report.js, test/public/defaults.js, test/public/eosReport/shift-leader-creation.test.js, test/public/logs/create.test.js
- Order magnets input Dipole first then solenoid in RC daily meeting template and SL EoS report
- Added inputs for magnets configuration of noon the day before in the RC daily meeting template
=> [O2B-1228] Improve magnets transitions in RC daily meeting log template

lib/public/components/common/panel/PanelComponent.js, lib/public/views/QcFlags/Create/qcFlagCreationComponent.js, lib/public/views/Runs/Details/RunDetailsModel.js, lib/public/views/Runs/Details/runDetailsComponent.js, test/public/defaults.js, test/public/qcFlags/forDataPassCreation.test.js, test/public/qcFlags/forSimulationPassCreation.test.js, test/public/runs/detail.test.js, test/public/runs/runsPerPeriod.overview.test.js
- Added a new tab in runs details to display trigger counters table
=> [O2B-1281] Display trigger counters in run details

lib/server/services/qualityControlFlag/QcFlagService.js, test/lib/server/services/qualityControlFlag/QcFlagService.test.js
- NA
- Fixed QC flag effective periods creation corner case and failing test
- NA
=> Fix QC flag effective periods creation corner case and failing test

lib/public/components/common/popover/PopoverEngine.js, lib/public/components/common/popover/popover.js
- Fixed bug of popover not being placed in the right position when using browser zoom
- Fixed popover not being resized when filtering drop-down options
- Fixed popover not being properly resized along cross axis when using browser zoom
- Fixed popover not being properly clipped when overflowing along cross axis
=> [O2B-1077] Several fixes in popover system

lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js
- Exclude the EoS report from the logs list in RC daily meeting minutes template
=> [O2B-1230] Exclude EoS report from RC daily meeting minutes template logs

lib/database/adapters/EnvironmentAdapter.js, lib/database/migrations/20240702134026-add-environment-raw-configuration.js, lib/database/models/environment.js, lib/database/models/typedefs/SequelizeEnvironment.js, lib/database/seeders/20220412122043-environments.js, lib/domain/dtos/CreateEnvironmentDto.js, lib/domain/entities/Environment.js, lib/public/views/Environments/Details/EnvironmentDetailsModel.js, lib/public/views/Environments/Details/EnvironmentDetailsPage.js, lib/server/controllers/gRPC/GRPCEnvironmentController.js, lib/usecases/environment/CreateEnvironmentUseCase.js, proto/environment.proto, test/api/environments.test.js, test/lib/server/services/environment/EnvironmentService.test.js, test/public/envs/detailsPage.test.js
- Added possibility to save raw configuration when creating an environment
- Display a new tab in environments details to show raw configuration
- Added `raw_configuration` column to environment table
=> [O2B-1189] Store environment configuration in the database

lib/public/views/Logs/Create/templates/onCallLogCreationConfiguration.js
- Added `ADJUST` beam mode option for on-call log template
=> [O2B-1305] Add adjust beam type in on-call template log options

lib/database/repositories/LhcFillRepository.js, lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js, lib/public/views/Logs/Create/templates/rcDailyMeetingConfiguration.js, lib/server/services/lhcFill/LhcFillService.js
- Format properly fill start and duration in RC daily meeting minutes template
- Fixed runs to check display to be in a panel as the other inputs
=> [O2B-1231] Improve RC daily meeting minutes formatting and fix fills list

test/public/runs/runsPerDataPass.overview.test.js
- NA
- Fixed randomly failing tests for Runs Per Data Pass Page
- NA
=> Fix randomly failing tests for Runs Per Data Pass Page

lib/public/components/qcFlags/qcSummaryColors.js, lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js, lib/server/services/qualityControlFlag/QcFlagService.js, test/api/qcFlags.test.js, test/lib/server/services/qualityControlFlag/QcFlagService.test.js, test/public/runs/runsPerDataPass.overview.test.js
- NA
- Fixed incorrect values of run coverage in QC summary
- Added handling of QC summary calculation for runs with missing timestamps
- NA
=> [O2B-1311] Invalida calculation in QC summary

test/public/envs/overview.test.js
- NA
- Fixed one test failing randomly
- NA
=> Fix randomly failing test

lib/public/components/common/selection/SelectionModel.js, lib/public/components/common/selection/dropdown/SelectionDropdownModel.js, lib/public/components/common/selection/picker/picker.js, lib/public/components/tag/tagPicker.js, lib/public/views/Logs/Create/logCreationComponent.js, lib/public/views/Runs/Details/editTagsPanel.js, test/public/logs/create.test.js
- Allow filtering tags in log creation and run edition
=> [O2B-1308] Add possibility to filter tags in log creation and run edition

lib/server/services/qualityControlFlag/QcFlagService.js, test/lib/server/services/qualityControlFlag/QcFlagService.test.js
- NA
- Fixed bug with QC flag deletion introduced in #1638
- NA
=> [O2B-1318] Bugfix QC flag deletion

package-lock.json, package.json
-
- bump of web-ui dependency to address security vulnerabilities
-
=> Bump WebUI patch version

lib/public/components/FlpRun/index.js, lib/public/views/Flps/ActiveColumns/flpsActiveColumns.js, lib/public/views/Runs/ActiveColumns/runsActiveColumns.js, lib/public/views/Runs/Details/runDetailsConfiguration.js
- Update labels for some of the run-details page and their value to improve readability of the numbers
=> [O2B-1321] Update Run Details labels and display values

lib/server/services/run/RunService.js, lib/server/services/run/createRun.js, lib/server/services/run/getRun.js
- NA
- Fixed usage of transaction in run creation
- NA
=> Fix run detectors creation

lib/server/services/qualityControlFlag/QcFlagService.js, test/lib/server/services/qualityControlFlag/QcFlagService.test.js
- NA
- Added missing associations to GAQ flags
- NA
=> [O2B-1274] Add missing associations to GAQ flags

lib/server/services/dataPasses/DataPassService.js, test/api/dataPasses.test.js, test/lib/server/services/dataPasses/DataPassService.test.js
- NA
- Added alphabetical sorting to GAQ detectors fetching method
- NA
=> [O2B-1274] Fix order by GAQ detectors

lib/database/migrations/20240718120539-add-type-column-to-detectors.js
- NA
- Change order of foreign key constraints creation for run_detectors table
- NA
=> Make sequelize migration more robust

lib/database/migrations/20240731134539-add-default-GAQ-detectors.js
- NA
- Fixed migration file adding default GAQ detectors
- NA
=> [O2B-1322] Fix adding default GAQ detectors

test/public/defaults.js, test/public/qcFlags/gaqOverview.test.js, test/public/qcFlags/index.js, test/scripts/test-qcFlags.js
- NA
- Fixed GAQ overview tests
- NA
=> Fix tests GAQ overview tests

lib/database/seeders/20200426144121-users.js, lib/database/seeders/20240404100811-qc-flags.js, lib/public/views/QcFlags/details/qcFlagDetailsConfiguration.js, lib/public/views/QcFlags/format/formatQcFlagCreatedBy.js, package.json, test/api/qcFlags.test.js, test/lib/server/services/qualityControlFlag/QcFlagService.test.js, test/public/qcFlags/detailsForDataPass.test.js
- Fixed QC flag origin display on details page
- Added Anonymous to users seeder and QC flag with origin to QC flags seeder
- NA
=> [O2B-1331] Bug fix: QC flag origin not displayed on details page

lib/database/seeders/20200511151010-tags.js, lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js, test/public/logs/create.test.js
- Updated p2info to P2INFO tag in rc daily template
=> [O2B-1328] Update p2info to P2INFO in daily meeting template

lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js
- Sort runs to be checked in ascending order in RC daily template
=> [O2B-1329] Order runs to be checked in ascending order in RC daily template

lib/public/views/Logs/Create/templates/RcDailyMeetingTemplate.js, test/public/logs/create.test.js
- Added EMC to list of detectors in RC daily template
=> [O2B-1330] Add EMC to list of detectors in RC daily template

lib/public/components/FlpRun/index.js, lib/public/views/Flps/ActiveColumns/flpsActiveColumns.js, lib/public/views/Runs/Details/runDetailsComponent.js, test/public/runs/detail.test.js
- Format properly FLP statistics
=> [O2B-1320] Fix number formatting in run details

test/public/defaults.js, test/public/qcFlags/gaqOverview.test.js
- NA
- Fixed randomness of one of GAQ overview tests
- NA
=> Fix randomness of GAQ overview test

lib/database/adapters/LhcFillAdapter.js, lib/database/migrations/20240902080430-add-fill-colliding-bunch-and-lumi.js, lib/database/models/lhcFill.js, lib/database/models/typedefs/SequelizeLhcFill.js, lib/domain/dtos/UpdateLhcFillDto.js, lib/domain/entities/LhcFill.js, lib/server/controllers/lhcFill.controller.js, lib/usecases/lhcFill/UpdateLhcFillUseCase.js, test/api/lhcFills.test.js, test/lib/usecases/lhcFill/UpdateLhcFillUseCase.test.js
- Per fill delivered lumi and colliding bunches can be defined
- Added columns colliding\_bunches\_count and delivered\_lumi columns to lhc\_fills
=> [O2B-1370] Store delivered lumi and colliding bunches per fill

lib/server/services/run/RunService.js
- FLP hosts list is now properly extracted when consuming ECS new run message
=> [O2B-1371] Store FLP from ECS kafka

lib/server/monalisa-synchronization/MonAlisaSynchronizer.js
- NA
- Fixed defining skimmingStage in ML synchronizer
- NA
=> Fix condition in ML synchronizer

lib/server/services/run/RunService.js
- Fixed log creation for detector EoR reason
=> [O2B-955] Use proper detector label to detect detector EoR reason

Dockerfile
- NA
- Removed failing alpine package from Dockerfile
- NA
=> [O2B-831] Remove failing alpine package in dockerfile

CHANGELOG.md, lib/server/services/run/getRunDefinition.js, proto/common.proto, test/lib/usecases/lhcFill/GetAllLhcFillsUseCase.test.js
- Fixed gRPC API for service LhcFill.getLast
=> [O2B-1381] Fix stable beams start/stop/duration typo (singular beam)

lib/database/seeders/20230124105627-environment-history.js, lib/server/services/environment/getEnvironmentsInPeriod.js, test/lib/server/services/environment/getEnvironmentsInPeriod.test.js
- Environments with status "DONE" are now considered to be ended
- N/A
- N/A
=> [O2B-1380] Add DONE environment status to the ones that closes environments

lib/public/utilities/formatting/formatSizeInBytes.js, lib/public/views/Flps/ActiveColumns/flpsActiveColumns.js, lib/usecases/run/GetFlpsByRunUseCase.js, test/public/defaults.js, test/public/runs/detail.test.js
- Display mean STF size and data rate per FLP
- N/A
- N/A
=> [O2B-1367] Display average STF size and data rate per FLP

lib/server/kafka/AliEcsSynchronizer.js, lib/server/services/run/RunService.js, proto/ecs/protos/common.proto
- Environments with `bookkept: false` in configuration are not stored
=> [O2B-1374] Store only environments with bookkept flag to true

lib/server/WebUiServer.js
- N/A
- BKP process do not crash anymore when database crash
- N/A
=> [O2B-1394] Survive to DB crash

lib/database/migrations/20231025101611-create-lhc-periods-view.js, lib/database/migrations/20241105125509-fix-physical-constants.js, test/api/lhcPeriodsStatistics.test.js, test/lib/server/services/lhcPeriod/LhcPeriodStatisticsService.test.js
- Fixed physical constants values which resulted in wrong AVG center of mass energy
- N/A
- Fixed physical constants values in database
=> [O2B-1399] Fix physical constants values

lib/config/services.js
- N/A
- Environment variable ENABLE_HOUSEKEEPING must be set to `true` (case-insensitive) to actually enable housekeeping
- N/A
=> [O2B-1415] Fix ENABLE_HOUSEKEEPING environment variable parsing

docker-compose.yml, lib/application.js, lib/config/services.js, lib/server/externalServicesSynchronization/ccdb/CcdbSynchronizer.js, lib/server/externalServicesSynchronization/monalisa/MonAlisaClient.js, lib/server/externalServicesSynchronization/monalisa/MonAlisaSynchronizer.js
- N/A
- Added more logs to external service synchronization (CCDB, MonALISA)
- N/A
=> [O2B-1417] Add more logs to services synchronization

Dockerfile
- N/A
- Updated docker ca-certificate dependency
- N/A
=> [O2B-831] Update ca-certificates for docker

lib/public/views/Home/Overview/HomePage.js, test/public/home/overview.test.js
- N/A
- Improved home page frontend tests to make them more robusts
- N/A
=> Fix home frontend tests randomly failing

lib/database/adapters/RunAdapter.js, lib/database/adapters/UserAdapter.js, lib/database/adapters/index.js, lib/database/models/run.js, lib/database/models/typedefs/SequelizeRun.js, lib/database/seeders/20200713103855-runs.js, lib/domain/entities/Run.js, lib/public/views/Runs/Details/runDetailsComponent.js, lib/usecases/run/GetRunUseCase.js, test/lib/usecases/run/GetRunUseCase.test.js, test/public/runs/detail.test.js
- Display run that started/stopped run in run details
- N/A
- N/A
=> [O2B-912] Display user that started/stopped run

test/public/defaults.js, test/public/qcFlagTypes/creation.test.js
- N/A
- Fix randomly failing QC flag types
- N/A
=> Fix QC flag types randomly failing

lib/public/components/Filters/RunsFilter/runNumbersFilter.js, lib/public/components/Filters/common/filters/RawTextFilterModel.js, lib/public/views/Runs/ActiveColumns/runsActiveColumns.js, lib/public/views/Runs/Overview/RunsOverviewModel.js, lib/public/views/Runs/Overview/RunsOverviewPage.js, lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js, test/public/runs/detail.test.js, test/public/runs/overview.test.js, test/public/runs/runsPerDataPass.overview.test.js
- N/A
- Improve run numbers filters in run overview
- N/A
=> [O2B-536] Improve runs overview run number filter

lib/domain/enums/BkpRoles.js, lib/public/domain/enums/BkpRoles.js, lib/public/models/UserRoleSelectionModel.js, lib/public/views/QcFlagTypes/Create/QcFlagTypeCreationPage.js, lib/public/views/QcFlagTypes/Overview/QcFlagTypesOverviewPage.js, lib/public/views/QcFlags/details/qcFlagDetailsComponent.js, lib/public/views/Runs/Overview/exportRunsTriggerAndModal.js, lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js, lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js, lib/public/views/Tags/Create/index.js, lib/public/views/Tags/Details/tagDetailsComponent.js, lib/server/controllers/qcFlag.controller.js, lib/server/routers/qcFlag.router.js, lib/server/services/qualityControlFlag/QcFlagService.js, test/api/qcFlags.test.js, test/lib/server/services/qualityControlFlag/QcFlagService.test.js, test/public/runs/runsPerDataPass.overview.test.js
- Added a button to discard all QC flags for a given data pass
- N/A
- N/A
=> [O2B-1429] Added button to discard all QC flags per data pass

lib/public/views/QcFlags/ForDataPass/QcFlagsForDataPassOverviewPage.js, lib/public/views/QcFlags/qcFlagsVisualization/qcFlagsChartComponent.js, test/public/qcFlags/detailsForDataPass.test.js
- Fixed the bug of QC flags chart height increasing on every rendering
- N/A
- N/A
=> Fix glitch in flags chart display height

lib/server/GRPCServer.js, lib/server/gRPC/bindGRPCController.js, test/gRPC/serviceImplementation.test.js
- N/A
- The binding of gRPC controllers has been sligtly refactored to make it easier to maintain
- N/A
=> [O2B-1437] Refactor gRPC service definition

lib/database/adapters/DataPassAdapter.js, lib/database/migrations/v1/20250328072732-add-datapass-freeze-flag.js, lib/database/models/dataPass.js, lib/database/models/typedefs/SequelizeDataPass.js, lib/database/models/typedefs/SequelizeQcFlagVerification.js, lib/domain/entities/DataPass.js, lib/domain/entities/qcFlagVerification.js, lib/public/components/qcFlags/qcFlagCreationPanelLink.js, lib/public/views/QcFlags/Create/QcFlagCreationModel.js, lib/public/views/QcFlags/Create/forDataPass/QcFlagCreationForDataPassPage.js, lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js, lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewModel.js, lib/public/views/Runs/RunPerDataPass/RunsPerDataPassOverviewPage.js, lib/server/controllers/dataPasses.controller.js, lib/server/externalServicesSynchronization/monalisa/MonAlisaClient.js, lib/server/routers/dataPasses.router.js, lib/server/services/dataPasses/DataPassService.js, lib/server/services/qualityControlFlag/QcFlagService.js, lib/server/services/run/RunService.js, lib/server/services/simulationPasses/SimulationPassService.js, test/api/dataPasses.test.js, test/api/qcFlags.test.js, test/lib/server/services/dataPasses/DataPassService.test.js, test/lib/server/services/qualityControlFlag/QcFlagService.test.js, test/public/runs/runsPerDataPass.overview.test.js
- Added possibility to lock data passes
- N/A
- Added `frozen` flag to datapasses table
=> [O2B-1407] Add possibility to lock RCT flags

test/scripts/parallel-local/custom-mocha-reporter.js, test/scripts/parallel-local/main.js, test/scripts/parallel-local/test-runner.js
=> Remove console.log from tests

lib/server/kafka/AliEcsSynchronizer.js, package-lock.json, package.json
- N/A
- the operation `trg.EnsureRunStop()` is followed as well as it may be the correct event notifying about the trigger stop in case of failure
- bump patch version of BKP
-
=> [OGUI-1447] Follow new ECS operation for trigger end timestamp

Dockerfile
- NA
- Update version of ca-certificates in Dockerfile
- NA
=> Update failing dependency

lib/database/adapters/RunAdapter.js, lib/public/views/Runs/ActiveColumns/runsActiveColumns.js
- Allow to export runs with colliding bunches count
- Na
- NA
=> [O2B-1293] Allow to export colliding bunches count

test/api/qcFlags.test.js, test/public/defaults.js, test/public/runs/navigationUtils.js, test/public/runs/overview.test.js
- NA
- Make runs overview tests more robust
- NA
=> Restructure Runs Overview Tests

lib/public/views/Runs/ActiveColumns/runDetectorsAsyncQcActiveColumns.js, test/public/defaults.js, test/public/runs/runsPerDataPass.overview.test.js
- Add information popup on AOT and MUON columns
- NA
- NA
=> [O2B-1473] Header description for AOT and Muon columns
